### ISSUE TITLE
Upgrade SpringBoot to 2.6.4

### ISSUE THREAD

**Issue by Jeeppler** [mercedes-benz/sechub#1057]
Upgrade to SpringBoot 2.6.3

- https://spring.io/blog/2022/01/20/spring-boot-2-6-3-is-now-available
- https://github.com/spring-projects/spring-boot/releases/tag/v2.6.3

**Comment by de-jcup** [comment]
Changed title to 2.6.4 - we will update to [v2.6.4](https://github.com/spring-projects/spring-boot/releases/tag/v2.6.4)
