### ISSUE TITLE
Change SecHub client linkout in Wiki to new mercedes-benz organization

### ISSUE THREAD

**Issue by icypixels** [mercedes-benz/sechub#1094]
https://github.com/mercedes-benz/sechub/wiki/Examples#jenkins-integration-example

The linkout to the SecHub Client points to a GitHub Page which was hosted on the "old" daimler organization.
Please adapt this link.

**Comment by sven-dmlr** [comment]
Hi @icypixels,
thanks for the hint. :+1: 
I fixed the links and names.
Now all the Links in the Wiki should work again.
