### ISSUE TITLE
Canceled Job shall trigger products to cancel ongoing operation

### ISSUE THREAD

**Issue by de-jcup** [mercedes-benz/sechub#111]
With #110 we introduce possibility to cancel jobs. The domain scan was not handled there. So this issue shall target the point.

Every Adapter should get a method to interrupt a job (by job UUID).
Either its not possible by the product/or the current situation (adapter just has an empty method) or the adapter tries to stop execution.

There shall be just a listening to the event "canceled job" and then reaction start inside "scan" domain.

**Comment by sven-dmlr** [comment]
Superseded and implemented within #1549 

Closing this issue.
