### ISSUE TITLE
Server: Improve error message on invalid projectID

### ISSUE THREAD

**Issue by sven-dmlr** [mercedes-benz/sechub#1120]
## Current situation:
Passing a projectID with not allowed characters results in a HTTP 401 (Unauthorized)
```bash
> sechub -project "../evil" scan
 _____           _   _       _
/  ___|         | | | |     | |
\ `--.  ___  ___| |_| |_   _| |__
 `--. \/ _ \/ __|  _  | | | | '_ \
/\__/ /  __/ (__| | | | |_| | |_) |
\____/ \___|\___\_| |_/\__,_|_.__/ Client Version 0.28.0-20220218142739

2022-03-07 18:05:29 (+01:00) Zipping folder: src (/home/myuser/test/src)
2022-03-07 18:05:29 (+01:00) Creating new sechub job
2022-03-07 18:05:30 (+01:00) ERROR: The SecHub server responded with HTTP status code '401 '
body=
Hint: Unauthorized - Please check if your SecHub credentials (userID and API-token) are valid.
```

## Problem:
The HTTP 401 with empty body is not helpful.
(The calling userID and api-token are correct)

## Wanted:
Suggest to give a HTTP 403 with a meaningful message in the response body.

From w3.org:
**403 Forbidden**
The server understood the request, but is refusing to fulfill it. Authorization will not help and the request SHOULD NOT be repeated. If the request method was not HEAD and the server wishes to make public why the request has not been fulfilled, it SHOULD describe the reason for the refusal in the entity. If the server does not wish to make this information available to the client, the status code 404 (Not Found) can be used instead.

**Comment by de-jcup** [comment]
The reason why this results in a 404 is, that we do only allow normlaized URLs.

After creating an integration test which tries to create a job with an "../evil" projectId, I got following result:


```
2022-03-10 17:40:02.251  WARN 34724 --- [0.1-8443-exec-8] c.m.s.s.l.DefaultSecurityLogService      : [SECURITY] [POTENTIAL INTRUSION]:
data=
{
  "type" : "POTENTIAL_INTRUSION",
  "clientIp" : "127.0.0.1",
  "message" : "Rejected request, reason:{}",
  "messageParameters" : [ "The request was rejected because the URL was not normalized." ],
  "requestURI" : "/api/project/../evil/job",
  "httpHeaders" : {
    "accept" : "text/plain, application/json, application/cbor, application/*+json, */*",
    "accept-encoding" : "gzip,deflate",
    "authorization" : "Basic aW***length:66",
    "connection" : "Keep-Alive",
    "content-length" : "37",
    "content-type" : "application/json",
    "cookie" : "JSESSIONID=1327F3A7A719F2DCC0B873FB067684A3",
    "host" : "localhost:8443",
    "user-agent" : "Apache-HttpClient/4.5.13 (Java/1.8.0_282)"
  },
  "sessionId" : "1327F3A7A719F2DCC0B873FB067684A3"
}
, message=Rejected request, reason:The request was rejected because the URL was not normalized.
2022-03-10 17:40:02.263  INFO 34724 --- [0.1-8443-exec-9] .s.c.IntegrationTestServerRestController : FROM INTEGRATION-TEST:
```

**Comment by de-jcup** [comment]
The mentioned 401 is because the spring boot firewall does not accept malformed URLs at all, which should not be changed, so I will close this issue.

But after reading the other related code, I have created #1134 to change all 406 assertion error to 400 as a follow up issue.
