### ISSUE TITLE
Improve UC_046 documentation (show example for fetched false-positive list)

### ISSUE THREAD

**Issue by company-jcup** [mercedes-benz/sechub#1122]
## Situation
The UC_46 is not describing the resulting output format of false positivel list - see 
https://mercedes-benz.github.io/sechub/latest/sechub-techdoc.html#section-usecase-UC_046

## Wanted
As a user/developer I want to have this information inside the documentation

## Solution
Improve documentation and add either an example snippet, or improve the RESTDOC output in general (which is the better way).

**Comment by de-jcup** [comment]
This should be automatically fixed when #1125 has been implemented.

**Comment by de-jcup** [comment]
Marked as duplicate. Will be fixed with PR #1138
