### ISSUE TITLE
Upgrade to Gradle 8.0

### ISSUE THREAD

**Issue by Jeeppler** [mercedes-benz/sechub#1123]
Switch to Gradle 8.0.

This issue depends on #1093.

**Comment by Jeeppler** [comment]
The team behind Gradle is working on Gradle 8.0 RC1: https://github.com/gradle/gradle/milestone/164

**Comment by de-jcup** [comment]
Remark about #1093
with https://github.com/mercedes-benz/sechub/issues/1093 the SecHub gradle build itself is now 8.0 compatible (no warnings). But when it comes to asciidoc generation, we have some warnings. It ssems the `asciidoc` gradle plugin itself has a problem here.
