### ISSUE TITLE
Client: exclude IDE's files per default

### ISSUE THREAD

**Issue by sven-dmlr** [mercedes-benz/sechub#1221]
## Current situation:
Some IDEs place files in the source tree. These files should be excluded per default.

## ToDo
Add these folders to the exclude list for source files:
- `.idea/`
- `.vscode/`

**Comment by Jeeppler** [comment]
Visual Studio uses a number of files to track projects: https://www.ibm.com/support/pages/visual-studionet-metadata-files-and-function-they-serve-when-integrated-clearcase

The `.gitignore` generated for VisualStudio using [gitignore.io](https://www.toptal.com/developers/gitignore) looks like this: https://www.toptal.com/developers/gitignore/api/visualstudio

For XCode it looks like this: https://www.toptal.com/developers/gitignore/api/xcode

I guess, not all of them have to be excluded. However, I am not using VisualStudio or XCode. Maybe, a developer who uses any of those IDEs can provide a better answer.

**Comment by de-jcup** [comment]
Hm... 

When somebody uses SecHub on a build server they will checkout the branch from their SCM...
When we do a `secret-scan` and inside a IDE file there is a project specific configuration (e.g. a (silly) plugin/extensions writes there the credentials for something (e.g. a database) this information would get lost.

Also it is often not a good way to checkin IDE specific files. At least for Intellij and Eclipse I would always prefer to setup the tooling by a gradle task or calling a maven goal to do the setup (or let it be done by plugin magic automatically).

**Comment by sven-dmlr** [comment]
Good point.

But the fact that IDE files exist on the Developer's computer does not automatically mean that they are in the repository. They could be excluded e.g. by `.gitignore`.

**Comment by sven-dmlr** [comment]
After discussion in the team, we decided not to implement this issue.
-> closing issue
