### ISSUE TITLE
Waiting for jobs to be done runs infinitely

### ISSUE THREAD

**Issue by lu-ei** [mercedes-benz/sechub#1253]
Hi,

since yesterday our scans with daimler-internal version run infinitely long with last message waiting for job to be done but nothing happens.

```
RUN SECHUB SCAN
 _____           _   _       _     
/  ___|         | | | |     | |    
\ `--.  ___  ___| |_| |_   _| |__  
 `--. \/ _ \/ __|  _  | | | | '_ \ 
/\__/ /  __/ (__| | | | |_| | |_) |
\____/ \___|\___\_| |_/\__,_|_.__/ Client Version 0.22.1-20201209171341

2022-04-19 07:13:52 (Z) Creating new sechub job
2022-04-19 07:13:52 (Z) Zipping folder: /var/build/Ubuntu0302/_work/83/s/ (/var/build/Ubuntu0302/_work/83/s)
2022-04-19 07:13:52 (Z) Uploading source zip file
2022-04-19 07:13:54 (Z) Approve sechub job
2022-04-19 07:13:54 (Z) Waiting for job 68d45bbe-87e7-4ffa-9b25-328dbe0bae9a to be done
```

API version: 1.0 
Project: svt

**Comment by Jeeppler** [comment]
@lu-ei thanks for creating an issue. Please be aware, that issues on GitHub.com are public.

Based on your Command Line output, I would first suggest you try a new client. The latest client version is: [v0.29.0](https://github.com/mercedes-benz/sechub/releases/tag/v0.29.0-client).

**Comment by sven-dmlr** [comment]
Hi @lu-ei ,
we checked the server logs and all looked fine.
I was able to download the report.

As @Jeeppler already proposed: Please try using the latest client.

-> If there are still issues, then please open a company-internal ticket. Thank you.

Closing this issue.
