### ISSUE TITLE
Increase PDS Product Identifier Length

### ISSUE THREAD

**Issue by Jeeppler** [mercedes-benz/sechub#1273]
The current length of the PDS Product Identifier is limited to 30 characters. This should be increased to at least 50. As `PDS_INTTEST_PRODUCT_LICENSESCAN` is too long.

**Comment by Jeeppler** [comment]
Increase the project identifier to 50 characters (50*3 = 150 in Postgres).

**Comment by winzj** [comment]
For SecHub we do not change the product identifier length, because we have only `enum` entries. On `PDS` side we this described problem and we will increase the database field length.
