### ISSUE TITLE
Evaluate SARIF model generation via JSON schema and integrate generated model into importer

### ISSUE THREAD

**Issue by de-jcup** [mercedes-benz/sechub#1303]
## Situation
We have much effort so support a working SARIF model and it is sometimes difficult to adopt the written specification into code - see #1299 for details.

But instead of #1299 we could simply generate a model by using the official JSON schema at 
https://github.com/oasis-tcs/sarif-spec/blob/master/Documents/CommitteeSpecifications/2.1.0/sarif-schema-2.1.0.json

For generation we could use https://github.com/joelittlejohn/jsonschema2pojo (Apache 2.0 License) which provides jackson annotations as well.

## Wanted 
Check how the generated SARIF model looks like and if it is working.
Also try to generation with Optional instead of null values.

## Solution
- create a new  branch
- integrate the `gradle` plugin for jsonschema2pojo inside `sechub-sarif`
- create a task which generates sources (with Optional instead of `null` if possible)
- generate the sources by `gradle` task in a way that we can provide multiple SARIF formats in future.
- try to integrate the new generated model into existing SARIF importer
- if this works well, create a PR

**Comment by winzj** [comment]
There is another link inside the oasis repo. This looks like the the schemata section:
https://github.com/oasis-tcs/sarif-spec/blob/main/Schemata/sarif-schema-2.1.0.json

**Comment by winzj** [comment]
Using the [json-schema](https://github.com/oasis-tcs/sarif-spec/blob/main/Schemata/sarif-schema-2.1.0.json) we generated a SARIF model which is now ready to use thanks to @de-jcup here:
https://mvnrepository.com/artifact/de.jcup.sarif.java/sarif-2.1.0/1.0.1
