### ISSUE TITLE
Replace project name in Jenkins pipeline with variable

### ISSUE THREAD

**Issue by Jeeppler** [mercedes-benz/sechub#1343]
Replace the `-project sechub` with a variable in `sechub -project sechub` and `sechub.exe -project sechub`:

~~~
void executeSecHubScan() {

     if (isUnix()) {
         sh "sechub -project sechub scan"
     } else {
         bat "sechub.exe -project sechub scan"
     }
}
~~~

for example: 

~~~
String projectName = "sechub";

void executeSecHubScan() {

     if (isUnix()) {
         sh "sechub -project projectName scan"
     } else {
         bat "sechub.exe -project projectName scan"
     }
}
~~~

The code snippet is from [continous-integration-multibranch-pipeline.jenkins](https://github.com/mercedes-benz/sechub/blob/develop/continous-integration-multibranch-pipeline.jenkins). The pipeline is used as example in the [documentation for Jenkins](https://github.com/mercedes-benz/sechub/wiki/Examples#jenkins-integration-example).

**Comment by ramazansakin** [comment]
Thanks @Jeeppler  :)
