### ISSUE TITLE
Single PDS + PMD

### ISSUE THREAD

**Issue by Jeeppler** [mercedes-benz/sechub#1353]
Create a single PDS + PMD Dockerfile and Docker-Compose file. This is a sub-issue of #764.

**Comment by Jeeppler** [comment]
@zigfridus I will assign you this issue. This is the issue for the work on `single pds + pmd`.

**Comment by Jeeppler** [comment]
@zigfridus Apparently, I have to wait until you commented on this issue, before I can assign you this task: https://github.blog/2019-06-25-assign-issues-to-issue-commenters/

**Comment by zigfridus** [comment]
@Jeeppler assign me to this issue please.
