### ISSUE TITLE
[PMD + PDS] Mock file

### ISSUE THREAD

**Issue by Jeeppler** [mercedes-benz/sechub#1358]
With #1353 PMD is now available as a SecHub PDS Solution. Meaning, that SecHub can scan with PMD. Most people, want to only scan their application to make sure to have little or even better no (security) findings in their source code.

However, if we wanted to test PMD we need some vulnerable code with security vulnerabilities (in this case weaknesses, to be precise). There are a number of ways to get code with vulnerabilities (sorted from less effort to more effort):

1. The tool provides a test data set.
2. Samples with weaknesses. For example, the NIST has a database with example files: https://samate.nist.gov/SARD/test-suites
3. Vulnerable applications. For example, OWASP VWAD has a list of applications: https://owasp.org/www-project-vulnerable-web-applications-directory/
4. Write examples.

Once we found a vulnerable example or wrote one, we can use it to scan and test the tool. Depending on the tool this can take some time. In case, we only want to test the integration between SecHub and PMD+PDS, we can simply return a pre-recorded result file.
To do this we:

1. Scan the example with the PDS+PMD solution (scan using different parameters, if optional parameters can influence the result).
2. Take the result file(s) and put it into the `mocks` folder in the PMD+PDS solution folder (`pmd/docker/mocks`).
3. Add a `PDS_PMD_MOCK` product in the `pds-config.json`. Add optional parameters, if the real product has some. 
4. Write a `pmd-mock.sh` script, which returns the per-recorded mock files. If you have different parameters which can have an influence on the result, return different mock files for each option.

Describing it is more difficult as it is. Have a look at the GoSec+PDS or Multi+PDS for examples.

Furthermore, the mock files can be used to test whether SecHub can read the results or not. SARIF and other standard formats can have large variations between the results, as each author implements the standard slightly different. SecHub contains many unit and integration tests, we can reuse the mock files in those tests.

Part of epic: #764

**Comment by Jeeppler** [comment]
PMD does have examples in their documentation for some of the security and quality issues: https://pmd.github.io/pmd/pmd_rules_java_security.html.

**Comment by zigfridus** [comment]
@Jeeppler assign me to this issue please.

**Comment by zigfridus** [comment]
Hello @Jeeppler 
I've crated the mock environment. How can I check if it works correctly?

**Comment by Jeeppler** [comment]
While calling `70-test.sh` you set the `PDS_PRODUCT_IDENTFIER` to `PDS_PMD_MOCK`:

~~~
export PDS_PRODUCT_IDENTFIER=PDS_PMD_MOCK
~~~

To test it you can use any Zip file and upload it. The result will always be the same, regardless of Zip file. For example, create an empty text file, compress (zip) it and run your test:

~~~
bash 70-test.sh empty-file.zip
~~~

if you want to test a variation of your product you can provide a JSON configuration file:

~~~
{
    "apiVersion" : "1.0",
    "sechubJobUUID": "288607bf-ac81-4088-842c-005d5702a9e9", 
    "productId": "PDS_PMD_MOCK",
    "parameters": [
        {
            "key" : "pmd.ruleset",
            "value" : "ALL" 
        }
    ]
}
~~~

and

~~~
bash 70-test.sh ~weaknesses.zip pmd-all.json
~~~

Basically, you call the mock-product the same way, you would be calling a real product. The only difference is, that the result is always the same regardless of the file uploaded. In case you have options you can test them as well.

**Comment by Jeeppler** [comment]
@zigfridus you can always create a pull-request draft with all the changes. This way, others can look over your work. Once you are ready you can set the pull-request to ready to review.
