### ISSUE TITLE
[PMD+PDS] Run multiple instances

### ISSUE THREAD

**Issue by Jeeppler** [mercedes-benz/sechub#1359]
To unlock even more power, we can run multiple instances of PMD+PDS at the same time. PDS can turn any security scanning tool into a distributed and scalable solution.  To achieve this, a database and data storage, to which all PMD+PDS instances have access to, is required. 

For a blueprint on how to do this have a look at: GoSec+PDS: `sechub-pds-solutions/gosec`. To do this locally, additional Bash and Docker-Compose scripts are needed. The `50-start-multiple-docker-compose.sh` script starts multiple PMD+PDS instances by using the help of a database docker container and load balancer. We use ngnix as reverse proxy for the local setup. A default user needs to be added to the database. In addition, there is a little bit of configuration work needed for the database and load balancer.

The second setup script `51-start-multiple-object-storage-docker-compose.sh` starts a S3 compatible object storage container in addition to the database container and load balancer. We use [SeaweedFS](https://github.com/chrislusf/seaweedfs) as S3 compatible object storage.

Part of epic: #764

**Comment by zigfridus** [comment]
@Jeeppler 
Assign me to this issue please.

**Comment by Jeeppler** [comment]
@zigfridus I assigned you the issue.

**Comment by zigfridus** [comment]
@Jeeppler 
review my PR please.
