### ISSUE TITLE
[PMD+PDS] Create a Helm Chart

### ISSUE THREAD

**Issue by Jeeppler** [mercedes-benz/sechub#1376]
Today, Kubernetes is one of the core technologies allowing DevOps team to deploy scalable solutions to a cluster of nodes in the cloud.

Many free and open source software (FOSS) security tools are designed as command line (CLI) tools, that is totally fine. However, to make them cluster ready SecHub developed the Product Delegation Server (PDS). PDS can turn any CLI tool into a cluster ready tool.

By creating a [Helm Chart](https://helm.sh/docs/) for the PMD+PDS solution it is possible to allow anyone to easily run the PMD+PDS in a Kubernetes cluster. By using SecHub and the PMD+PDS Helm Chart in combination, one can run many scans in parallel.

Creating a Helm Chart is not difficult. Helm Charts are a number of configuration files bundled together in a folder. The templates in a Helm folder are nothing more than normal Kubernetes files. The only difference is, that it is possible to use [Go-Templating](https://golangdocs.com/templates-in-golang) inside of them, which makes them very flexible and powerful.
In addition, Helm requires some additional Metadata files.

To get started have a look at our Helm Chart for GoSec+PDS: https://github.com/mercedes-benz/sechub/tree/develop/sechub-pds-solutions/gosec/helm/pds-gosec. This chart can be used as blueprint, by simply copying it and adjusting the parameters to PMD+PDS.

To get a better understanding of Helm Charts and how to develop them have a look at the many resources Helm already provides:

- [Quickstart Guide](https://helm.sh/docs/intro/quickstart/)
- [Chart Template Guide](https://helm.sh/docs/chart_template_guide/getting_started/)
- [How-to Guides](https://helm.sh/docs/howto/)

Keep in mind this step can be difficult, as running a Kubernetes cluster locally is quite resource intensive. There are several projects trying to reduce the effort:

- [K3S](https://k3s.io/)
- [kind](https://kind.sigs.k8s.io/)

The previous steps so far:

- Create a single PMD+PDS instance #1353 
- Create mocks PMD+PDS #1358
- Multiple PMD+PDS instances #1359 

This is a sub issue of #764

**Comment by zigfridus** [comment]
@Jeeppler 
please review my PR.

**Comment by zigfridus** [comment]
@Jeeppler any problems with my PR ?

**Comment by Jeeppler** [comment]
@zigfridus sorry, for not getting this done faster. I will try to get this PR done as quick as possible. I reviewed it and it looks fine. Additionally, I want to try if it works in a K8s cluster. Give me a little bit of time.
