### ISSUE TITLE
Rename spring boot values / environment variables from "sechub.pds.*" to "pds.*"

### ISSUE THREAD

**Issue by company-jcup** [mercedes-benz/sechub#1429]
## Situation
Currently we have spring boot values with "sechub.pds.*" 
It is not clear at a glimpse if the configuration is on SecHub or PDS side

## Wanted
- At PDS side we want only spring boot values  starting with "pds.*"
- If we have any special parts at SecHub side for the product executor, we still want to have those spring boot values  starting with "sechub.pds\*"
- Executor config parameters for PDS side do always start with "pds.config.*"
- Executor config parameters for PDS but on SecHub side do always start with "sechub.pds.config.*"

## Solution

- [x] Collect changes inside this issue 
- [X] Describe migration steps inside issue 
- [x] Rename all relevant spring boot values on SecHub Side
- [x] Rename all relevant spring boot values on PDS Side
- [x] Rename all relevant parameter constants on SecHub Side
- [x] Rename all relevant parameter constants on PDS Side
- [x] Check/adapt Helm charts
- [x] Check/adapt `run.sh` scripts in container images
- [x] Check generated documentation

**Comment by de-jcup** [comment]
## Summary
### What was done
Inside this issue following was done:

- pds_config.adoc changed all "sechub.pds" to "pds"
- replaced all "-Dsechub.pds" with "-Dpds"
- replaced all "SECHUB_PDS_" with "PDS_"
- replaced all `sechub.pds with `pds
- replaced in every *.adoc `sechub.pds` with `pds`
- replaced all `${sechub.pds` with `${pds`
- replaced in every `*.properties` all `sechub.pds` with `pds`

At SecHub side we had already only "sechub.adapter.pds.*" which was not changed.

### Migration steps for updating an existing SecHub infrastructure
- in your executor configurations: change the parameters which start with "sechub.pds" to "pds" 
- in your IDE: change your launch configurations accordingly
  - "-Dsechub.pds.*" to "-Dpds.*"
  - Environment entries like "SECHUB_PDS_*" to "PDS_*"
