### ISSUE TITLE
Provide GitHub Action for SecHub

### ISSUE THREAD

**Issue by Jeeppler** [mercedes-benz/sechub#1443]
Provide a GitHub Action for SecHub on the public marketplace: https://github.com/marketplace?type=actions. A public action can easily be used by the community.

(Changes by @de-jcup) :
Here we only provide an initial SecHub GitHub Action which provides the standard report output formats `json`, `html`

Further issues will provide addtional features (e.g. SARIF support, tables etc. )

**Comment by de-jcup** [comment]
## Definition
Here a definition of the wanted features, pathes etc.

### Actions to implement
We want two actions at the beginning;
- scan
- markFalsePositives

### Pathes
The actions will be settled NOT inside the root folder, but inside dedicated subfolders
We create a sub folder `github-actions` inside root folder and inside this folder subfolders for the dedicated actions:
```
/github-actions/${nameOfAction}/
```
Example:
``` 
/github-actions/scan
```

This means that the action can be used in a worflow via following one liner:
```
- uses mercedes-benz/sechub/github-actions/scan
```

### Shared folder
If possible we try to have a shared folder where common used parts can be put in and reused.

### Parameters
- API token is mandatory parameter (and can be set by user via a github secret)
- Other parameters can be defined by `sechub.json` file
- If possible introduce some parameters inside action to have override possiblity
