### ISSUE TITLE
Upgrade dependencies to Spring Boot 2.7.1

### ISSUE THREAD

**Issue by Jeeppler** [mercedes-benz/sechub#1448]
Upgrade to Spring Boot 2.7.1: https://github.com/spring-projects/spring-boot/releases/tag/v2.7.1

We did upgrade to Spring Boot 2.7.1, but we did not upgrade the dependencies.
See: #915

**Comment by de-jcup** [comment]
We should just ignore/ close this one and do directly
-  #1484

**Comment by Jeeppler** [comment]
@de-jcup I already did this and it was reviewed by @winzj. Just forgot to close it.
