### ISSUE TITLE
Create Demo/Test App for OpenAPI Java Client

### ISSUE THREAD

**Issue by Jeeppler** [mercedes-benz/sechub#1506]
Create a demo/test application which uses the OpenAPI Java client.

**Comment by zigfridus** [comment]
@Jeeppler 
I would like to ask you to explain a little bit this task. 
Do you need a JavaFX or Swing application or something else?
Are there any documentation about this task I have to read?
Thanks

**Comment by Jeeppler** [comment]
@zigfridus sure, here are more details about the issue/task. 

The OpenAPI Java client is a library, which is generated from the OpenAPI file using [OpenAPI Generator](https://openapi-generator.tech/).

The OpenAPI file is generated from [REST Docs](https://spring.io/projects/spring-restdocs) tests using a [REST Docs OpenAPI plugin](https://github.com/ePages-de/restdocs-api-spec).

The pipeline looks like this:

~~~
Spring Boot Rest Doc Tests ----> Generate OpenAPI file ----> OpenAPI file (JSON) ----> OpenAPI Generator ----> Java client library
~~~

To generate the Java client library the following commands are necessary:

~~~
// generates OpenAPI file into sechub-doc/build/api-spec/openapi3.json
./gradlew ensureLocalhostCertificate
./gradlew generateOpenapi

// build Java client library the jar can be found in sechub-api-java/gen/build/libs/sechub-api-java-0.0.0.jar
./gradlew :sechub-api-java:buildAPIJava
~~~

My suggestion would be to write a small CLI tool which allows one to interact with the server. For example, a CLI tool which allows one to check whether the server is alive or not and list all users. The objective is not to make a full Java CLI client (we already have a CLI client written in Go), instead the objective is to get some understanding of whether the generated library works at all. A small CLI client which implements an anonymous and a privileged command suffices. 

To understand how to run the SecHub server follow the Quickstart Guide:  https://mercedes-benz.github.io/sechub/latest/sechub-quickstart-guide.html.

The REST API is well documented and can be found here: https://mercedes-benz.github.io/sechub/latest/sechub-restapi.html.

Feel free to ask any questions which you still have.

**Comment by Jeeppler** [comment]
I assigned you the task. I hope this is okay for you.

**Comment by zigfridus** [comment]
@Jeeppler 
I try to generate openapi3.json using
`./gradlew generateOpenapi`
but get a lot the same testing errors:
> java.lang.IllegalStateException: Could not initialize plugin: interface org.mockito.plugins.MockMaker
> Could not initialize inline Byte Buddy mock maker.
> It appears as if your JDK does not supply a working agent attachment mechanism.
> Java               : 11
> JVM vendor name    : Debian
> JVM vendor version : 11.0.16+8-post-Debian-1deb11u1
> JVM name           : OpenJDK 64-Bit Server VM
> JVM version        : 11.0.16+8-post-Debian-1deb11u1
> JVM info           : mixed mode, sharing
> OS name            : Linux
> OS version         : 5.10.102.1-microsoft-standard-WSL2
> Caused by: java.lang.IllegalStateException: Could not self-attach to current VM using external process

It seems to me the problem is in my virtual machine. I'm using Debian on the Windows 10 host. I would like to ask what environment do you use for the Sechub building?

**Comment by Jeeppler** [comment]
We are using Debian/Ubuntu to build SecHub. 

As far as I can see you are using `OS version : 5.10.102.1-microsoft-standard-WSL2`, meaning you are not actually using Debian with a Linux Kernel, but with the Windows Subsystem for Linux version 2.

My suggestion would be to try building it in a container. A simple Debian 11 container running an infinite `while` loop and then shell into the container to execute the quickstart guide commands. Or you can use a virtual machine.

From my own experience working with WSL2, it can cause unexpected behaviors. It is different from a real Linux environment.

**Comment by zigfridus** [comment]
@Jeeppler 
Thank you for your last advice. The use Debian in VirtualBox took away the last problem.

**Comment by zigfridus** [comment]
@Jeeppler 
Maybe I found a little bug. 
When I build Java client library with

> ./gradlew :sechub-api-java:buildAPIJava

I see this error

> /mnt/sechub/sechub-api-java/gen/src/main/java/com/mercedesbenz/sechub/api/java/model/ProjectWhiteList.java:41: error: class ProjectWhitelist is public, should be declared in a file named ProjectWhitelist.java
> public class ProjectWhitelist implements Serializable {

It seems to me that there is a misspelling in the generated class name. It should be 
`public class ProjectWhiteList implements Serializable {`
but not
`public class ProjectWhitelist implements Serializable {`

**Comment by Jeeppler** [comment]
@zigfridus I was unable to reproduce the issue. I suspect the issue is, the commit state of your own fork.

Your own forked version of SecHub is 193 commits behind: "This branch is [193 commits behind](https://github.com/zigfridus/sechub/compare/develop...mercedes-benz:sechub:develop) mercedes-benz:develop."

Please update your fork of SecHub: https://github.com/zigfridus/sechub. Your fork should only be a few commits back.

Have a look at these articles on how to do it:

- https://stackoverflow.com/questions/7244321/how-do-i-update-or-sync-a-forked-repository-on-github
- https://medium.com/@sahoosunilkumar/how-to-update-a-fork-in-git-95a7daadc14e

After you updated the fork, try to build the client again.

**Comment by Jeeppler** [comment]
@zigfridus let me know, whether that fixed the issue.

**Comment by zigfridus** [comment]
@Jeeppler 
Unfortunately updating my fork didn't help.

> git remote -v
> origin  https://github.com/mercedes-benz/sechub.git (fetch)
> origin  https://github.com/mercedes-benz/sechub.git (push)
> upstream        https://github.com/zigfridus/sechub (fetch)
> upstream        https://github.com/zigfridus/sechub (push)

I see the last closed request in my sechub:
> git log
> commit 8d830e999ca3a11d8bab07cbb878507d3578949e (HEAD -> develop, upstream/develop)
> Merge: c822c305 9d20fa8e
> Author: Sven <59958584+sven-dmlr@users.noreply.github.com>
> **Date:   Wed Aug 17 16:47:19 2022 +0200**

I found out that after changing the values ProjectWhitelist to the ProjectWhiteList in the previously generated **openapi3.json**, I can build the client without errors.
```
"$ref": "#/components/schemas/ProjectWhitelist"
"ProjectWhiteList": {
    "title": "ProjectWhitelist",
```

**Comment by Jeeppler** [comment]
@zigfridus good job.

A small hint. The SecHub server is now containerized. Have a look into the `sechub-solution` folder and it has some setup scripts for projects/pds-solutions as well. You could use it for the Demo/Test of the OpenAPI Java client.

**Comment by zigfridus** [comment]
@Jeeppler thank you for the hint.

**Comment by zigfridus** [comment]
@Jeeppler 
I have a question. 
I can use in the CLI client, I working on, the **AnonymousApi** library and find out if a server is alive.
```
AnonymousApi anonymousApiInstance = new AnonymousApi(defaultClient);
anonymousApiInstance.anonymousCheckAliveGet();
```

But I can't find in the documentation of OpenApi Java Client, how to provide the admin_id (int-test_superadmin) and admin_password (int-test_superadmin-pwd) for the **AdminApi** library. 
Can you help me with it?

**Comment by zigfridus** [comment]
After some exploring I guess that credentials should be provided via ApiClient. I was trying use basic authentication. 
```
HttpBasicAuth basicAuthentication = new HttpBasicAuth();
basicAuthentication.setUsername("int-test_superadmin");
basicAuthentication.setPassword("int-test_superadmin-pwd");

Map<String, Authentication> authMap = new HashMap<>();
authMap.put("basic", basicAuthentication);

ApiClient apiClient = new ApiClient(authMap);
apiClient.setBasePath("https://localhost:8443");

AdminApi adminApiInstance = new AdminApi(apiClient);
try {
           System.out.println(adminApiInstance.adminListsAllUsers());
} catch (ApiException e) {
            System.err.println("Exception when calling AdminApi#adminListsAllUsers");
            System.err.println("Status code: " + e.getCode());
            System.err.println("Reason: " + e.getResponseBody());
            System.err.println("Response headers: " + e.getResponseHeaders());
            e.printStackTrace();
}
```

But this attempt failed. I've got the same error:

> Exception when calling AdminApi#adminListsAllUsers
> Status code: 401
> Reason: {"status":401,"error":"Unauthorized","message":"Unauthorized","details":[],"timeStamp":"Wed Aug 24 17:53:00 EEST 2022"}

I get stuck in this and still need your advice @Jeeppler.
Thanks

**Comment by Jeeppler** [comment]
@zigfridus sorry, for my late reply. The S3 upload problem is keeping me busy.

Your code is correct. However, the problem is, there is no information in the open API file that we are using basic authentication for `adminListsAllUsers` or any other Admin API. Meaning, you found a bug.

The security information should be in the OpenAPI file definition. The security information in the OpenAPI file should look similar to: https://swagger.io/docs/specification/authentication/basic-authentication/.

SecHub uses [Spring REST Docs](https://docs.spring.io/spring-restdocs/docs/current/reference/html5/) for the API documentation. To generate the OpenAPI file the [com.epages.restdocs-api-spec](https://github.com/ePages-de/restdocs-api-spec) plugin is used.

There are two main tasks:

1. Open an issue describing, that the basic authentication information ismissing.
2. Figure out how to add the basic authentication information to OpenAPI.

Let me know if you want to do any of the tasks or if I shall do them.

**Comment by Jeeppler** [comment]
@zigfridus I created an issue for the missing authentication information in OpenAPI: #1581.

**Comment by zigfridus** [comment]
@Jeeppler 
Ok, I'll try to resolve this authentication bug.

**Comment by Jeeppler** [comment]
@zigfridus I am already on it.

**Comment by zigfridus** [comment]
@Jeeppler 
Is better for me to wait until you resolve the issue #1581 or start to work on another issue?

**Comment by Jeeppler** [comment]
@zigfridus you can continue with this issue. I opened a pull request for the missing OpenAPI headers: https://github.com/mercedes-benz/sechub/pull/1593.

**Comment by zigfridus** [comment]
@Jeeppler 
I fetched your branch #1593 and build the new OpenApi Java Client. The admin authentication works right now.
Thanks

**Comment by Jeeppler** [comment]
@zigfridus thanks for testing it. Glad to hear it works.

**Comment by zigfridus** [comment]
@Jeeppler 
I would like to ask where should I put my small CLI? In which Sechub module?
Also I would like to know how to provide the constants (server path, admin username and password) for the CLI.
Should it be a config file, environment variables, program arguments or something else?

**Comment by Jeeppler** [comment]
We use a domain-driven design as our architecture style for SecHub. Oversimplified: what belongs together is in the same folder. In your case, your demo app should go into the `sechub-api-java` folder.

 In fact, there is already a class called `SecHubClient.java` in `sechub-api-java/src/main/java/com/mercedesbenz/sechub/api/java`. This class is intended to wrap around the generated AdminApi and the AnonymousApi. Providing an easy to use interface for users (other developers). The SecHubClient knows something about the SecHub report model. The SecHubClient.java is intended as a library, not a CLI tool.

To answer your questions, your code should go into `sechub-api-java/src/main/java/com/mercedesbenz/sechub/api/java/demo/cli`. The CLI should accept parameters passed as arguments and environment variable. 

You can have a look at:

- `sechub-analyzer-cli` - a small CLI tool which analyzes if there is a `NOSECHUB` or `END-NOSECHUB` comment in code. It uses Apache Commons CLI.
- `sechub-wrapper-owasp-zap` - a wrapper around the API of OWASP ZAP. It uses `jcommander` to parse the command line parameters.

Both are small CLI tools, which you can look at on how they are build using Gradle and how the dependency management works. As they are both standalone CLI applications.

Looking into the future. SecHub needs a web UI. For the web UI SecHub needs a `SecHubClient`-Java library. The  demo app is important to showcase how to use the `SecHubClient`-Java library, especially for people wanting to integrate with SecHub from Java.

**Comment by zigfridus** [comment]
@Jeeppler 
I created the small CLI tool. I hope this is what you need. I used some sources from the **sechub-wrapper-owasp-zap**.  I liked the way they are created. 
Please review my PR.
