### ISSUE TITLE
 Describe in quick start guide that this is only for developers

### ISSUE THREAD

**Issue by de-jcup** [mercedes-benz/sechub#1519]
## Situation

At https://mercedes-benz.github.io/sechub/latest/sechub-quickstart-guide.html we describe the first steps (from a developer or administrator perspective)

But ... When some users wants to start with SecHub they are sometimes confused and try to start an integration test server instead of reading the client manual at https://mercedes-benz.github.io/sechub/latest/sechub-client.html

## Wanted
The quickstart guide shall adress the problem by
- describe the target audience
- link to the client online help or mention the client documentation at least

**Comment by sven-dmlr** [comment]
Besides pointing out this, we should add a chapter to the quick start guide which describes how to get a SecHub server running.
That's what most people might be looking for.

E.g.:
```bash
# Download server jar from releases
mkdir tmp-storage
export SECHUB_STORAGE_SHAREDVOLUME_UPLOAD_DIR="`pwd`/tmp-storage"
export SPRING_PROFILES_ACTIVE=integrationtest,mocked_products,h2
java -jar sechub-server-<version>.jar
```

**Comment by sven-dmlr** [comment]
The developer quickstart guide has been renamed to `sechub-developer-quickstart-guide.html` recently.
