### ISSUE TITLE
User registration send an email at signup

### ISSUE THREAD

**Issue by Jeeppler** [mercedes-benz/sechub#156]
Users can register themselves as described in use case [UC_001-User self registration](https://daimler.github.io/sechub/latest/sechub-architecture.html#section-usecase-UC_001). All administrators get an email that the user registered. However, the user does not get an email confirming the registration. 

An administrator has to approve the user (see [UC_003-Admin applies self registration](https://daimler.github.io/sechub/latest/sechub-architecture.html#section-usecase-UC_003)). Without getting an email, the user might not know, that the registration attempt was successful. 

A problem which can occur is that malicious actors might try to register millions of users to do some sort of "denial of service" attack. However, `UC_001-User self registration` and `UC_003-Admin applies self registration` are vulnerable to the same sort of attack, except that the administrators will get a list with millions of sign ups + emails. To avoid this kind of abuse there should be an option to disable the user self signup feature.

**Comment by de-jcup** [comment]
SecHub does allow only one email-adress per user. So at least the vulnerability against the DoS attack described above is a little bit reduced.

@Jeeppler : Please create another issue for the DoS switch - its a good idea but its a separate issue.
This issue is just about the email sending

**Comment by Jeeppler** [comment]
@de-jcup as requested a new issue regarding the "DoS" switch: #161.

**Comment by de-jcup** [comment]
The email **may only** be **SENT ONE TIME** when a new self registration entry is written to database - so only if not existing before. This is necessary to prevent email bomb attacks over sechub REST API...

**Comment by zigfridus** [comment]
@Jeeppler 
I would like to ask what profiles do you use for the debugging SecHub main project?

**Comment by Jeeppler** [comment]
I have multiple run configurations in SecHub. The most basic one is called `SecHubServerApplication (INTEGRATION TEST - H2)`.

Main:

~~~
com.mercedesbenz.sechub.SecHubServerApplication
~~~

I use the following `VM arguments`*:

~~~
-Dspring.profiles.active=mocked_products,h2,integrationtest
-Dsechub.server.debug=true
-Dsechub.storage.sharedvolume.upload.dir=/home/user/.sechub/sharedvolume
-Dsechub.targettype.detection.intranet.hostname.endswith=intranet.example.org
-Dsechub.config.trigger.nextjob.initialdelay=0
~~~

* VM arguments are for the JVM. Those are the arguments with which the SecHub server is getting started.

`mocked_products` - no real products are called
`h2` - use the embedded H2 database (no separate database required)
`integrationtest` - start the  server with a standard user/password and self-signed embedded HTTPS certificate. The integration test profile is used in the [SecHub Quickstart Guide](https://mercedes-benz.github.io/sechub/latest/sechub-quickstart-guide.html) as well.

For debugging, you simply set the break point in your IDE. You can then use unit or integration tests to execute the functionality you are looking at. If you want to trigger the "real" behavior you can trigger it via `sechub-api.sh` script or by using the Developer UI.

From a technical perspective, using unit tests to trigger the behavior is the easiest, because you can set your break points and start the unit test in debug mode. However, from a user perspective using the `sechub-api.sh` is the easiest, because there is a lot of documentation for it ([usecases](https://mercedes-benz.github.io/sechub/latest/sechub-architecture.html#section-usecases), [REST API](https://mercedes-benz.github.io/sechub/latest/sechub-restapi.html)) and the `sechub-api.sh` script.

**Comment by zigfridus** [comment]
@Jeeppler 
Thank you

**Comment by Jeeppler** [comment]
There are two tasks:

1. The user should get an email send to his/her/their email address once the admin approves the signup (user feedback that the signup was accepted)
2. It should be possible to disable the signup feature. -> You could create a new issue for this. 
 
Disabling the signup feature entirely would make it impossible to signup users and trigger that an email gets send to them. As a result, the email bomb attack would be prevented.

#### The attack scenario imagined here is:

Actor: intended or unintended actor

Attack: Uses a list of email addresses and does a signup for each email address.

Consequence: The attack would result in a large amount of emails send from the SecHub instance

Solution: Disable the signup feature

Mitigation: Risk avoidance.

**Comment by zigfridus** [comment]
@Jeeppler 

Relatively to the task 1.
According to the debug logs the user should receive the email that the signup was accepted:

`INFO 6825 --- [xecutor_thread1] c.m.s.d.n.email.MockEmailService         : sending email: subject=SecHub user account created; to=new-user@example.org; from=mocked.from.sechub@example.org;`
`INFO 6825 --- [xecutor_thread1] c.m.s.d.n.email.MockEmailService         : resolved messages:0 for user:new-user@example.org`
`INFO 6825 --- [xecutor_thread1] c.m.s.d.n.email.MockEmailService         : Send TO target:new-user@example.org [ 1 ]: subject:'SecHub user account created', `

I tested it with help of the Developer Admin UI.

The email sends from this method:
informUserAboutSignupAccepted(User user)

Or am I missing something in this task.  :(

**Comment by Jeeppler** [comment]
@zigfridus you might be right. I created this issue a few years ago. Give me some time to have an in depth look into it.
While I am doing it, you can start with another issue if you like.

**Comment by Jeeppler** [comment]
related issue: #161

**Comment by zigfridus** [comment]
@Jeeppler 
Thank you for the detailed explanation and sorry for the delay. A lot of work.
Please review my PR.
