### ISSUE TITLE
Containerized SecHub Production Mode + Certificate

### ISSUE THREAD

**Issue by Jeeppler** [mercedes-benz/sechub#1566]
Add the ability to start SecHub in production mode. Until now it only starts in dev/localserver mode. The dev/localserver uses a self-generated TLS certificate.

Add the possibility to provide an external certificate and start the containerized SecHub in production mode.

Part of: #320

**Comment by sven-dmlr** [comment]
Already done.
See `sechub-solution/helm/sechub-server/values.yaml` line 72
