### ISSUE TITLE
OpenAPI missing authentication information

### ISSUE THREAD

**Issue by Jeeppler** [mercedes-benz/sechub#1581]
# Problem

The OpenAPI file does not contain any authentication information. As a result, the generated Java client for API endpoints requiring authentication does not work (for more information see: #1506).

# Solution

Add the authentication information for basic auth to the OpenAPI file. SecHub uses basic authentication (with TLS) for the API calls. The OpenAPI file is generated from [Spring RestDoc](https://spring.io/projects/spring-restdocs) tests using the [`restdocs-api-spec`](https://github.com/ePages-de/restdocs-api-spec) plugin. 

To add the authentication information one has to add them either to the RestDoc tests or use the capabilities of the `restdocs-api-spec` plugin.

NOTE: Similar issue was already opened #274

**Comment by Jeeppler** [comment]
here is an example on how to document a basic auth header: https://docs.spring.io/spring-restdocs/docs/current/reference/html5/#documenting-your-api-http-headers

**Comment by zigfridus** [comment]
@Jeeppler 
Please assign me to this issue.
