### ISSUE TITLE
Build test suite for containerized SecHub

### ISSUE THREAD

**Issue by Jeeppler** [mercedes-benz/sechub#1596]
Create a small test suite testing the containerized SecHub. The test should test all three build modes using Java 11 and Java 17.

Using Bash is sufficient for the test suite.

**Comment by therealelyayo** [comment]
Hello,
has this been fixed ?

**Comment by Jeeppler** [comment]
@de-jcup and @sven-dmlr please have a look.

**Comment by sven-dmlr** [comment]
Hello @therealelyayo ,
thanks for asking.
We are aiming for using a local Kubernetes like Minikube for testing.
We will discuss in the team if this issue can be closed in favor of above.

**Comment by sven-dmlr** [comment]
Discussion finished.
-> we close this issue
-> local Kubernetes -> #3067

**Comment by Jeeppler** [comment]
@sven-dmlr I think there is a fundamental miss understanding. The intention of this issue was to test the creation of the container build process. There are three technically different ways to build the container: download, build and copy and each can be build with different versions of Java. 
The intention of this issue is to build some automation around the build process. As a result, the reference to the local Kubernetes solution is misleading, as the image needs to be build before being able to use Helm charts in a local Kubernetes.
