### ISSUE TITLE
Tutorial SecHub + GoSec

### ISSUE THREAD

**Issue by Jeeppler** [mercedes-benz/sechub#1646]
Explain how to get started with SecHub + GoSec from a users perspective.

The steps should be:

1. Start the SecHub container using the `sechub-solution/01-start-single-docker-compose.sh`
2. Start the GoSec + PDS container `sechub-pds-solutions/05-start-single-sechub-network-docker-compose.sh`
3. Setup the necessary project, profile etc. with `sechub-solution/8000-setup-gosec.sh`. Explain, what the setup script does.
4. Start a scan with the `sechub` client and some test repository. 
5. Explain how to download both the HTML and JSON report
6. Install the VSCodium Plugin
7. Show how to load the JSON report into the VSCodium SecHub plugin.

The tutorial file should be located in: `sechub-doc/src/docs/asciidoc/sechub-getting-started.adoc`

NOTE: The tutorial will be limited to Linux (Debian/Ubuntu) users only.

Part of: #154

**Comment by Jeeppler** [comment]
@expp121 please comment on this issue.

**Comment by expp121** [comment]
> @expp121 please comment on this issue.

Hi!

**Comment by Jeeppler** [comment]
Please use this repository: https://github.com/Contrast-Security-OSS/go-test-bench

**Comment by Jeeppler** [comment]
Please write all the Bash/command line snippets into separate Bash files and use include statements to add them into the `sechub-getting-started.adoc` file. The objective is to run all steps automatically.
