### ISSUE TITLE
SecHub ignores package with name test

### ISSUE THREAD

**Issue by anshu-j-behera** [mercedes-benz/sechub#1674]
## Problem 
SecHub ignore package test in my main folder.

I wanted to create a test-utils lib with following structure:
```
├── src
│   ├── main
│   │   ├── com.foo.bar.test
│   │   │    ├──  testutlis.kt
```
Running a sechub scan returned the follwing error:
Zipping folder: src/main (/home/user/kotlin/test-utils/src/main)Zipfile has no content!

Changing the name of a package to something like testutils resolved the issue. 

## Wanted
SecHub doesn't ignore packages in main

**Comment by sven-dmlr** [comment]
> @sven-dmlr are we excluding to broadly on the client side?

In https://github.com/mercedes-benz/sechub/blob/develop/sechub-cli/src/mercedes-benz.com/sechub/cli/constants.go#L44 you can see which folders are ignored by the client:
```
// DefaultSourceCodeExcludeDirPatterns - Define directory patterns to exclude from zip file:
// - code in directories named "test" is not considered to end up in the binary
// - also ignore ".git" directory
// - ignore "node_modules" directories which may contain millions of lines of library code
var DefaultSourceCodeExcludeDirPatterns = []string{"**/test/**", "**/.git/**", "**/node_modules/**"}
```

Files with extension `.kt` are considered as source code and should be added to the upload zip:
https://github.com/mercedes-benz/sechub/blob/develop/sechub-cli/script/supported-source-extensions.txt#L13

**Comment by sven-dmlr** [comment]
I did a test creating a file in the mentioned directory structure:
`src/main/com.foo.bar.test/testutlis.kt`

The client created and uploaded a zip file as expected.

**Comment by anshu-j-behera** [comment]
> I did a test creating a file in the mentioned directory structure: `src/main/com.foo.bar.test/testutlis.kt`
> 
> The client created and uploaded a zip file as expected.

Hey first of all thanks for the quick responses. 

I guess there is a slight misunderstanding regarding the folder structure. For brevity I had the described the directories representing my groupId at one level. I see how that could be so easily misread, apologies for that.

My directory structure is src/main/com/foo/bar/test/testutlis.kt

**Comment by sven-dmlr** [comment]
@anshu-j-behera thanks for the clarification.
The default exclude `**/test/**` matches here.
So in your case you should set SECHUB_IGNORE_DEFAULT_EXCLUDES environment variable to 'true'.
```bash
export SECHUB_IGNORE_DEFAULT_EXCLUDES=true
```

Closing this issue...
