### ISSUE TITLE
`batch_` tables are missing since server v0.35.x

### ISSUE THREAD

**Issue by sven-dmlr** [mercedes-benz/sechub#1691]
## Problem
After starting the SecHub server jar, all needed database tables should be created automatically.
But when running server v0.35.x on a new environment, these tables are missing:
```
 Schema |               Name                |   Type   | Owner
--------+-----------------------------------+----------+--------
 sechub | batch_job_execution               | table    | sechub
 sechub | batch_job_execution_context       | table    | sechub
 sechub | batch_job_execution_params        | table    | sechub
 sechub | batch_job_execution_seq           | sequence | sechub
 sechub | batch_job_instance                | table    | sechub
 sechub | batch_job_seq                     | sequence | sechub
 sechub | batch_step_execution              | table    | sechub
 sechub | batch_step_execution_context      | table    | sechub
 sechub | batch_step_execution_seq          | sequence | sechub
```
So a scan fails with database complaints about non-existing tables.

Suspect: The Spring-Boot upgrade to version 2.7.3 (the tables in question belong to Spring Boot batch functionality)

**Comment by de-jcup** [comment]
### How to reproduce locally

1. Start `LocalTestPostgrSQLStarter.java`
2. Start SecHub server locally  with `-Dspring.profiles.active=mocked_products,postgres,integrationtest`
3. Execute `FullScanDataScenario3SecHubClientIntTest`

The test will fail

Running the Execute `FullScanDataScenario3SecHubClientIntTest` with a SecHub server using H2 database does always work!

**Comment by de-jcup** [comment]
Problem found, the spring setup "spring.batch.jdbc.initialize-schema" is deprecated and was replaced in 2.7.x, see 

https://github.com/spring-projects/spring-boot/blob/f185b0767a71c2c326769bafea5966b677d6be00/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/batch/BatchProperties.java#L72-L82


```java
	/**
	 * Return whether the schema should be initialized.
	 * @return the initialization mode
	 * @deprecated since 2.5.0 for removal in 2.7.0 in favor of
	 * {@link Jdbc#getInitializeSchema()}
	 */
	@Deprecated
	@DeprecatedConfigurationProperty(replacement = "spring.batch.jdbc.initialize-schema")
	public DataSourceInitializationMode getInitializeSchema() {
		return this.jdbc.getInitializeSchema();
	}	
```

Removal was in Spring Boot 2.7.0 . 
Unfortunately I did not found anything mentioned inside migration guides at https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.7-Release-Notes
or at https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.5-Release-Notes where the deprecation has been started

The new value is mentioned at 
https://docs.spring.io/spring-boot/docs/current/reference/html/howto.html
