### ISSUE TITLE
PDS solutions: Make heartbeat logging configurable

### ISSUE THREAD

**Issue by sven-dmlr** [mercedes-benz/sechub#1694]
## ToDo:
In #1555, the possibility to suppress the PDS heartbeat logging was introduced.

In order to make use of it,
* the `run.sh` of the PDS base-image needs to check if an environment variable `PDS_HEARTBEAT_LOGGING` is set. If not: default to `"true"` for `sechub.pds.config.heartbeat.verbose.logging.enabled`.
* set the environment variable in `deployment.yaml` of each PDS-solution that uses the base-image (currently only pds-gosec)
* add the setting to the values.yaml of the Helm chart

**Comment by haerter-tss** [comment]
I also increased the chart version in chart.yaml
