### ISSUE TITLE
Make environment variables in executor config usable

### ISSUE THREAD

**Issue by haerter-tss** [mercedes-benz/sechub#1712]
# Situation
Environment variables like `env:MY_CHECKMARX_PASSWORD` within a executor config in SecHub do not work. For example:
```
pds.checkmarx.password=env:MY_CHECKMARX_PASSWORD
pds.checkmarx.userid=env:MY_CHECKMARX_USERID
```

# Wanted
Environment variables should be usable.

**Comment by de-jcup** [comment]
The implementation will change, so it will be possible to use environment entries in every parameter inside an executor configuration.
