### ISSUE TITLE
Containerize SecHub Client

### ISSUE THREAD

**Issue by Jeeppler** [mercedes-benz/sechub#1718]
Containerize the SecHub Client and provide scripts to build it. In addition, provide the containerized image on ghcr.io (GitHub Container Registry).

**Comment by Jeeppler** [comment]
@sven-dmlr is this done?

**Comment by sven-dmlr** [comment]
See here: https://github.com/mercedes-benz/sechub/packages 
-> not yet

**Comment by sven-dmlr** [comment]
closing this issue as duplicate to #2337
