### ISSUE TITLE
PDS-OWASP-ZAP: owasp process in separate container

### ISSUE THREAD

**Issue by sven-dmlr** [mercedes-benz/sechub#1757]
## Situation
pds-owasp-zap image:
Currently we have a Kubernetes POD with one container where both, the PDS _and_ the OWASP-ZAP processes run.

## Problem
We do not want this. The Kubernetes rule of thumb is: "only one process per container".

In this case, Kubernetes wouldn't notice when the OWASP-ZAP process dies.

## Solution
Create a POD with two containers:
* container1: PDS server (small with few ressources)
* container2: OWASP-ZAP server process (what alive check can we use here for Kubernetes?)

**Comment by winzj** [comment]
As we discussed, we can start the OWASP-ZAP for each scan and do a shutdown and clean up after every scan. To achieve this we could extend the `owasp-zap.sh` inside the PDS-Solution. The second step is already done by the `owasp-zap.sh` script:

- [ ] 1. Starting up OWASP-ZAP server and waiting for OWASP-ZAP to start
- [ ] 2. Execute DAST scan
- [ ] 3. Shutdown OWASP-ZAP after scan and cleanup old session data
