### ISSUE TITLE
[Tern] Tern + Scancode

### ISSUE THREAD

**Issue by Jeeppler** [mercedes-benz/sechub#1827]
Combine Scancode-Toolkit and Tern in container.

**Comment by Jeeppler** [comment]
Not able to test it because of https://github.com/nexB/scancode-toolkit/issues/3171.

**Comment by pombredanne** [comment]
@Jeeppler ScanCode should install alright now as https://github.com/nexB/scancode-toolkit/issues/3171 is fixed. 
Side note: you may fancy looking at https://github.com/nexB/scancode.io/ for containers and VMs and https://github.com/nexb/vulnerablecode vulnerabilities.

**Comment by Jeeppler** [comment]
Blocked by bug: https://github.com/tern-tools/tern/issues/1202.
