### ISSUE TITLE
Some scripts cause issues on MacOS (Bash 3.2)

### ISSUE THREAD

**Issue by jplewa** [mercedes-benz/sechub#1859]
# Problem
MacOS by default uses an older version of Bash (in my case it's `3.2.57(1)-release`). Some of the scripts in this repository are not compatible with that. Additionally, the `SecHubClientExecutor` class only knows how to handle Windows and Linux when deciding which SecHub binary to use.

# Solution
1. Update scripts to use features that are backward compatible between Bash 3.X, 4.X, and 5.X.
2. Update `SecHubClientExecutor` to detect other operating systems and architectures.

**Comment by Jeeppler** [comment]
@jplewa thanks for opening the issue. I assigned you to this issue.

In case of questions, @sven-dmlr can probably assist you.
