### ISSUE TITLE
The OpenAPI code generation fails on MacOS due to case sensitivity

### ISSUE THREAD

**Issue by jplewa** [mercedes-benz/sechub#1866]
# Problem

On my MacOS computer the class `ProjectWhitelist` ends up in a file called `ProjectWhiteList.java` and the code does not compile.

<img width="1015" alt="image" src="https://user-images.githubusercontent.com/34098778/212955734-b88da66b-0194-4bc6-9c31-0029ee959e6e.png">

<details>
<summary>Click here for stacktrace</summary>

```
> Task :compileJava FAILED
/Users/jplewa/IdeaProjects/sechub/sechub-api-java/gen/src/main/java/com/mercedesbenz/sechub/api/java/model/ProjectWhiteList.java:40: error: class ProjectWhitelist is public, should be declared in a file named ProjectWhitelist.java
public class ProjectWhitelist implements Serializable {
       ^
/Users/jplewa/IdeaProjects/sechub/sechub-api-java/gen/src/main/java/com/mercedesbenz/sechub/api/java/model/Project.java:26: error: cannot find symbol
import com.mercedesbenz.sechub.api.java.model.ProjectWhiteList;
                                             ^
  symbol:   class ProjectWhiteList
  location: package com.mercedesbenz.sechub.api.java.model
/Users/jplewa/IdeaProjects/sechub/sechub-api-java/gen/src/main/java/com/mercedesbenz/sechub/api/java/model/Project.java:64: error: cannot find symbol
  private ProjectWhiteList whiteList;
          ^
  symbol:   class ProjectWhiteList
  location: class Project
/Users/jplewa/IdeaProjects/sechub/sechub-api-java/gen/src/main/java/com/mercedesbenz/sechub/api/java/model/Project.java:199: error: cannot find symbol
  public Project whiteList(ProjectWhiteList whiteList) {
                           ^
  symbol:   class ProjectWhiteList
  location: class Project
/Users/jplewa/IdeaProjects/sechub/sechub-api-java/gen/src/main/java/com/mercedesbenz/sechub/api/java/model/Project.java:213: error: cannot find symbol
  public ProjectWhiteList getWhiteList() {
         ^
  symbol:   class ProjectWhiteList
  location: class Project
/Users/jplewa/IdeaProjects/sechub/sechub-api-java/gen/src/main/java/com/mercedesbenz/sechub/api/java/model/Project.java:220: error: cannot find symbol
  public void setWhiteList(ProjectWhiteList whiteList) {
                           ^
  symbol:   class ProjectWhiteList
  location: class Project
```
</details>

# Solution

The spelling of `whiteList` vs `whitelist` needs to be made consistent.

**Comment by de-jcup** [comment]
Thank you - this is a bug/flaw. Fascinating that this does not matter at my Linux machine with eclipse. 
Maybe you want to fix it and create a PR ?

**Comment by jplewa** [comment]
> Fascinating that this does not matter at my Linux machine with eclipse.

MacOS is case insensitive by default (so `file.txt` and `File.txt` are the same file) and Linux is case sensitive. I just run the code generation task on my personal Linux computer and it looks like there's two classes: `ProjectWhitelist` and `ProjectWhiteList`. On MacOS one presumably overwrites the other, on Linux they coexist.

>  Maybe you want to fix it and create a PR ?

I've played around with this a little bit, but I don't have the fix ready yet. Are you okay with the API changing?
