### ISSUE TITLE
Incorrect handling of `Excludes` in `ZipConfig` and `TarConfig`

### ISSUE THREAD

**Issue by jplewa** [mercedes-benz/sechub#1867]
# Problem

The code for `FilePathMatch` includes the following comment:

```go
// FilePathMatch - This method provides ANT like selectors.
// See https://ant.apache.org/manual/dirtasks.html
// For example: "**/a*.txt" will accept
//               - "/home/tester/xyz/a1234.txt"
//               - "a1b.txt`
```

However, the current implementation doesn't really follow the linked specification. Specifically, the following test cases fail: 
<img width="986" alt="Screenshot 2023-01-17 at 18 02 11" src="https://user-images.githubusercontent.com/34098778/212965348-e116cd88-a200-4102-8236-d1d35deec60e.png">
Source: https://ant.apache.org/manual/dirtasks.html#patterns

<img width="1024" alt="Screenshot 2023-01-17 at 18 07 47" src="https://user-images.githubusercontent.com/34098778/212965355-baf3985b-2bbb-4f5b-8e0f-62a9c11ee1f5.png">

# Solution

I suggest replacing this flawed custom implementation with an external library such as [this one](https://github.com/bmatcuk/doublestar).

**Comment by sven-dmlr** [comment]
@jplewa 
The review needs to be discussed in the core team (as accepting this PR would break existing functionality which is already used). Will take some more time... :clock11:

**Comment by jplewa** [comment]
> @jplewa The review needs to be discussed in the core team (as accepting this PR would break existing functionality which is already used). Will take some more time... 🕚

Sure, I understand, it's not a small change. 

FYI, the current implementation causes one of the tests to fail on MacOS, specifically this one (from `zip_test.go`):

```go
func TestZipFileCanBeCreated_with_exclude_patterns_applied(t *testing.T) {
	/* prepare */
	dir := sechubUtil.InitializeTestTempDir(t)
	defer os.RemoveAll(dir)

	dirname1 := dir + "/sub1"
	dirname2 := dir + "/sub2"
	dirname3 := dir + "/sub2/sub3"

	sechubUtil.CreateTestDirectory(dirname1, 0755, t)
	sechubUtil.CreateTestDirectory(dirname2, 0755, t)
	sechubUtil.CreateTestDirectory(dirname3, 0755, t)

	filename0 := dirname1 + "/file0.txt"
	filename1 := dirname1 + "/file1.txt"
	filename2 := dirname2 + "/file2.txt"
	filename3 := dirname3 + "/file3.txt"

	content := []byte("Hello world!\n")
	sechubUtil.CreateTestFile(filename0, 0644, content, t)
	sechubUtil.CreateTestFile(filename1, 0644, content, t)
	sechubUtil.CreateTestFile(filename2, 0644, content, t)
	sechubUtil.CreateTestFile(filename3, 0644, content, t)

	path := dir + "/testoutput.zip"
	newZipFile, _ := os.Create(path)
	zipWriter := zip.NewWriter(newZipFile)

	config := ZipConfig{
		ZipFileName:        path,
		ZipWriter:          zipWriter,
		PrefixInZip:        "",
		Folders:            []string{dirname1, dirname2},
		Excludes:           []string{"**/file3.txt", "**/f*0*.txt"},
		SourceCodePatterns: []string{".txt"},
	}

	/* execute */
	err := Zip(&config)
	zipWriter.Close()
	newZipFile.Close()

	/* test */
	sechubUtil.Check(err, t)

	sechubUtil.AssertFileExists(path, t)
	sechubUtil.AssertMinimalFileSize(path, 300, t) // check if zip file is empty

	list := readContentOfZipFileTest(path, t)

	sechubUtil.AssertContainsNot(list, strings.TrimPrefix(filename0, "/"), t) // this file may not be inside, because excluded! (/sub1/file0.txt)
	sechubUtil.AssertContains(list, strings.TrimPrefix(filename1, "/"), t)    // this must remain
	sechubUtil.AssertContains(list, strings.TrimPrefix(filename2, "/"), t)    // this must remain
	sechubUtil.AssertContainsNot(list, strings.TrimPrefix(filename3, "/"), t) // this file may not be inside, because excluded!
	sechubUtil.AssertSize(list, 2, t)
}
```

What happens is that temporary files get placed in a directory called `/var/folders/7t/4c40hycs62g6ms5l8qql3nhr0000gn/T/sechub-cli-temp2190648875`, so the full path for `file1.txt` is `/var/folders/7t/4c40hycs62g6ms5l8qql3nhr0000gn/T/sechub-cli-temp2190648875/sub1/file1.txt`.

The pattern `**/f*0*.txt` is then turned into the regex `^.*/f.*0.*\.txt$` and that regex matches the path of every single file inside the `sechub-cli-temp2190648875` directory, because the `f` matches the `f` in `folders` and the `0` matches one of the zeros in the random directory names (and everything else is covered by the asterisks). The resulting zip is then completely empty and the test fails. See:  https://regex101.com/r/CydmKr/1

**Comment by sven-dmlr** [comment]
@jplewa Finally we have made up our minds:
* your PR will be accepted. We request some minor changes. I'll add them to the PR itself.

* main problem was, that a pattern like `*.java` for all Java source files in any directory would be no more supported.
  * Many users are currently using this.
  * So we want to keep this functionality. It will be added in a separate task after merging your PR.

* 2nd thing: Until now we intentionally avoided the use of external Go libraries because of these reasons:
  * Originally this came from the weak library mechanism Go had back in 2019.
  * Another advantage is, that you do not need an internet connection to compile the SecHub client. Just a local Go installation works.
  * External libs could embed security weaknesses into our code
  * -> due to the fact that the SecHub client only calls the server's api, we accept that risk and add the `bmatcuk/doublestar` library

**Comment by jplewa** [comment]
> * It's definitely an advantage to support the ANT pattern matching syntax completely

> * main problem was, that a pattern like `*.java` for all Java source files in any directory would be no more supported.
>   * Many users are currently using this.
>   * So we want to keep this functionality. It will be added in a separate task after merging your PR.

I'm not sure if I understand how this is going to work? Like, what's the difference between `**` and `*` then? Maybe it might make more sense to move away from ANT pattern matching and follow your own format where `*` is a wildcard that can match anything?

**Comment by sven-dmlr** [comment]
The idea is:
If the pattern does not contain a `/`, then put `**/` in front.
(`*.java` will then turn into `**/*.java`)
Then call doublestar.PathMatch().

**Comment by sven-dmlr** [comment]
Your example would not match `/a/b/whatever/c/d.java`. That's okay.

I only want `*.xyz` to work. The rest (as soon as directory separators are involved) should comply with the ANT standard.
