### ISSUE TITLE
Make Helm chart work with Docker image from sechub-solution

### ISSUE THREAD

**Issue by sven-dmlr** [mercedes-benz/sechub#1881]
## Problem
As discussed [here](https://github.com/mercedes-benz/sechub/issues/1567#issuecomment-1397963332):
* Currently there is no Docker image uploaded to ghcr.io/mercedes-benz/sechub/server. So the Helm Chart does not work with the default values.yaml.
* When building the Docker image from `sechub-solution/docker/`, the deployment with the Helm chart fails.

## ToDo
* update `run.sh` script so it is deployable with the Helm chart.
* Provide a Docker image of current SecHub server on ghcr.io/mercedes-benz/sechub/server

**Comment by ddzikon** [comment]
Hello @sven-dmlr
thank you for creating this follow-up issue regarding matters we [previously discussed](https://github.com/mercedes-benz/sechub/issues/1567#issuecomment-1398089111).

I would like to ask a few questions:
- do you happen to have an update on this issue regarding publication of Docker image for SecHub server and internal version of `run.sh` script?
- are currently internal versions of `run.sh` scripts planned to be made public for external contributions?

**Comment by sven-dmlr** [comment]
Hello @ddzikon 
sure: we will make our internal `run.sh` public - just as we did for the PDS-solutions.
For us, it make no sense to maintain two versions. :-)
It will be added along with this issue.
