### ISSUE TITLE
Automatically remove old scans

### ISSUE THREAD

**Issue by de-jcup** [mercedes-benz/sechub#19]
### About
To prevent full hard drives there should be a option to automatically remove old scan data.

## Wanted
As an administrator I can configure a "auto cleanup configuration" and after which age a Job and it's data will be automatically dropped.

#### Domain:administration
- [x] REST API for admin domain
- [x] Stores new configuration inside database 
- [x] An event with message id `AUTO_CLEANUP_CONFIGURATION_CHANGED`is triggered containing the calculated days for auto cleaning
- [x] Introduce a `AdministrationConfig` database table like already exist for scheduler : `SchedulerConfig` (adopt behavior, just for administration domain)
- [x] Enhance `AdministrationConfig` and introduce time field  `auto_cleanup_in_days`  - per default 0, means auto cleanup disabled

#### Domain: administration
- [x] REST API for admin domain
- [ ] Open API generation check
- [x] When no cleanup configuration existed before, a default will be returned with "0 month" - so still being disabled

#### Domain: scan
- [x] Rename old `ScanConfig` to `ScanMappingConfig` and all related parts (like services etc.) - will be done with #1059 
- [x] Introduce new `ScanConfig` and adopt like done inside  introduce time field  `auto_cleanup_in_days`  - per default 0, means auto cleanup disabled
- [x] on `AUTO_CLEANUP_CONFIGURATION_CHANGED` the days for cleanup are fetched from event and stored in db
- [x] Introduce `ScanAutoCleanupTriggerService` which is annotated with @schedule and is configurable by SpringValue annotion
- [x]  delete old `scan_product_result` entries 
- [x]  delete old `scan_project_log` entries 
- [x]  we currently do **NOT** delete `scan_report` entries at the moment, this will be done with #1010 because currently we can only use these database rows for statistics

#### Domain: schedule
- [x] on `AUTO_CLEANUP_CONFIGURATION_CHANGED` the days for cleanup are fetched from event and stored in db
- [x] Introduce `ScheduleAutoCleanupTriggerService` which is annotated with @schedule and is configurable by SpringValue annotion
- [x]  drops old schedule_sechub_job entries 

#### Domain: administration
- [x] on `AUTO_CLEANUP_CONFIGURATION_CHANGED` the days for cleanup are fetched from event and stored in db
- [x] Introduce a `AdministrationAutoCleanupConfig` which represents the auto cleanup configuration
      This configuration contains a "remove-jobs-older-than" field which contains a "time-unit" and "amount" entry.
- [x] Introduce `AdministrationAutoCleanupTriggerService` which is annotated with @schedule and is configurable by SpringValue annotion. Does use the `AdministrationConfigService` to fetch data
- [x] `AdministrationAutoCleanupService` : deletes old adm_job_information entries 

## Documentation
- [x] Rest doc
- [x] Use case documentation are descriptive (+ don't forget the technical use cases)
- [x] Short explanation of concept "auto cleanup" inside "concepts"
- [ ] The format of the time unit can be defined in "days", "weeks", "month", "years". This must be documented

## Integration test
- [x]  setup an integration test (difficult but should be possible)

**Comment by company-jcup** [comment]
We will not remove scan_report table entries - so we have at least statistic data.

Product result entries will be automatically deleted after the timeperiod

**Comment by company-jcup** [comment]
I think this could be done with simple DELETE SQL statements with date period restrictions (ENDED...)
