### ISSUE TITLE
SecHub Client - Cancel job

### ISSUE THREAD

**Issue by Jeeppler** [mercedes-benz/sechub#1909]
# Problem

The user should be able to cancel a job from the SecHub CLI.

User scenario:

- The user started a job
- The user realized it was a mistake (file to big, wrong branch etc.)
- The user user has to wait until the job ended

# Solution

The user should be able to stop an ongoing scan by providing the job uuid.

~~~
sechub -jobUUID 72e00a5a-52c6-470c-b24f-1bad4fe6958b stopScan
~~~

This is especially important for webScan or other scans which take several minutes or even hours.

**Comment by sven-dmlr** [comment]
Can be implemented as soon as the SecHub server supports the use case "user cancels job".
Currently only admins can cancel jobs,

**Comment by sven-dmlr** [comment]
Closing this issue for now.
We'll have to wait until the SecHub server supports cancelling.
Once the server feature is implemented then the client will also support this.
