### ISSUE TITLE
Deploy pds-solutions in `localserver` mode

### ISSUE THREAD

**Issue by sven-dmlr** [mercedes-benz/sechub#1917]
## ToDo:
Please check the Helm charts of all pds-solutions (pds-cloc should be done already) and

* remove `pds.startMode` out of the Helm chart's `values.yaml` and set it fixed to `localserver` in the deployment template.

See https://github.com/mercedes-benz/sechub/pull/1916/files#r1097611399

**Comment by Jeeppler** [comment]
@sven-dmlr why? 

`Localserver` is a Spring profile which uses a local self-signed TLS certificate. The next evolutionary step would be to start the server in production server mode. However, that would require a mechanism to provide TLS certificates to the PDS.

Furthermore, there is a debug mode which allows one to prevent the PDS server from starting and simply starts the container. This is nice if the PDS server crashes and one wants to inspect the reason why.

**Comment by sven-dmlr** [comment]
As discussed:
* currently, only `localserver` is in use. As soon as a profile like `production` can be used, the `values.yaml` will be extended.
  (then also settings like a SSL server certificate need to be needed)
* for keeping the container running after a crash:
  * in Kubernetes, you can use set `pds.keepContainerAliveAfterPDSCrashed` to `true` in the values.yaml file.
  * for local testing, you could specify `--entrypoint /bin/bash` to your `docker run` command

**Comment by sven-dmlr** [comment]
Won't do this now.
Will open a new issue if necessary.
