### ISSUE TITLE
Upgrade to Docker Compose CLI V2 (sechub-solution)

### ISSUE THREAD

**Issue by expp121** [mercedes-benz/sechub#1922]
### Situation
`sechub-solution` folder contains bash scripts, which use Docker Compose CLI V1 commands. They won't be supported after the end of June 2023 and will be removed from all Docker Desktop versions.
![image](https://user-images.githubusercontent.com/29148934/217559061-ab7a295d-9c04-48d7-bb81-53561bbd02a7.png)
source: https://docs.docker.com/compose/
### Wanted
Upgrade all scripts to Docker Compose CLI V2

### Solution
Change `docker-compose` to `docker compose`

**Comment by Jeeppler** [comment]
@expp121 thanks for taking this on.
