### ISSUE TITLE
Unable to change local ports on docker-compose startscripts

### ISSUE THREAD

**Issue by de-jcup** [mercedes-benz/sechub#1965]
## Situation
While testing #1937  I tried to start locally
- Local postgres instance
- SecHub integration test server (using local postgres)
- PDS integration test server
- PDS cloc solution by docker compose

The idea was to start a local postgres, execute the integration tests, change the test executors (use real PDS cloc) and start again and check the outputs inside database and on log files.

But both PDS instances run per default on port 8444.
I tried to change the server port adresses for the PDS solution, but there seems to be  no way to achieve this for the docker-compose variants.

I tried to change 
- .env
- .env-local

and define there something like `SERVER_PORT=8544` but it did not work.

## Wanted
For local development it would be nice to be able to customize the  ports for PDS docker compose instances via parameters.

**Comment by Jeeppler** [comment]
To be able to customize the ports, the parameter needs to be set in the docker compose file.

**Comment by Jeeppler** [comment]
Fixed it in: #1980
