### ISSUE TITLE
Improve startup text of PDS and SecHub

### ISSUE THREAD

**Issue by haerter-tss** [mercedes-benz/sechub#2026]
## Problem:
There is currently no way of knowing which default parameters for the PDS solutions are set and what the exact default value is. 

## Solution:
When starting a PDS solution it would be nice if all default parameters and their values would be shown.

### Bonus:
It would be cool if there was some sort of PDS logo in ASCII art that will be shown on boot :)

**Comment by de-jcup** [comment]
A good idea, but I think the default parameters should be only logged at debug level. So available at development time.

And the logo ... nice ;-)

**Comment by de-jcup** [comment]
We will do

- [ ] Add custom banner for SecHub server
- [ ] Add custom banner for PDS
- [ ] Each banner will show the application version and also the spring boot version
- [ ] Show up PDS defaults (cannot be sensitive data) inside logs when PDS is started

**Comment by de-jcup** [comment]
![image](https://github.com/mercedes-benz/sechub/assets/11644753/3efb521e-dfae-4248-8347-25737f6f0294)

**Comment by de-jcup** [comment]
![image](https://github.com/mercedes-benz/sechub/assets/11644753/993ed00c-ec26-4c47-bcba-c5fef14e490e)

**Comment by de-jcup** [comment]
![image](https://github.com/mercedes-benz/sechub/assets/11644753/c8965452-ae3f-4749-8aa5-5697b13d53ed)

**Comment by de-jcup** [comment]
![image](https://github.com/mercedes-benz/sechub/assets/11644753/d73b9aba-12cf-4513-89fe-cd7da84fb2dc)
