### ISSUE TITLE
Number of waiting jobs when calling `server_status` is misleading

### ISSUE THREAD

**Issue by sven-dmlr** [mercedes-benz/sechub#2039]
## Situation:
When calling `server_status`, one of the returned keys is `status.scheduler.jobs.waiting`.
The value is the SUM of the execution states `INITIALIZING` + `READY_TO_START` (from database table `schedule_sechub_job` ).

## Problem:
I would expect to see only the `READY_TO_START` number.
(In state INITIALIZING, the user can still do uploads etc. So these jobs are imho not "waiting" to be scheduled)

## Solution:
I propose to count only the jobs in execution state `READY_TO_START`.

**Comment by de-jcup** [comment]
The responsible query part is here:

https://github.com/mercedes-benz/sechub/blob/ffb5822696bdf404c8fd72d95cd237b6cf376bd6/sechub-schedule/src/main/java/com/mercedesbenz/sechub/domain/schedule/job/SecHubJobRepository.java#L29-L32

This result will be used by `SchedulerStatusService` to build a `SchedulerMessage` which is received by `admin` domain

**Comment by de-jcup** [comment]
## Discussions /Ideas
After talking with @sven-dmlr we have agreed on that it makes no sense to use 
`INITIALIZING` + `READY_TO_START` for "waiting". The only "waiting" parts are when `READY_TO_START`.

But... this means we do not need the property handling of "start" and "end" but instead we just need the 
execution states from scheduler side!

This leads to another question: why not just provide "all" + all execution states at all?"

## Result
- We change the `SchedulerStatusEntryKeys` identifiers so they are more identifiable to the execution state:
- We keep
   SCHEDULER_ENABLED("status.scheduler.enabled"),
   SCHEDULER_JOBS_ALL("status.scheduler.jobs.all"),
- We rename
    SCHEDULER_JOBS_RUNNING("status.scheduler.jobs.running"), 
   to:    SCHEDULER_JOBS_INITIALIZING("status.scheduler.jobs.initializing"
- We rename
    SCHEDULER_JOBS_WAITING("status.scheduler.jobs.waiting"),
   to SCHEDULER_JOBS_READY_TO_START("status.scheduler.jobs.ready_to_start"),
- We introduce generally always SCHEDULER_JOBS_${NAME_OF_EXECUTION_STATE_ENUM} with 
  "status.scheduler.jobs.${NAME_OF_EXECUTION_STATE_ENUM.toLowerCase()}
