### ISSUE TITLE
SecHub Client: Set labels via client

### ISSUE THREAD

**Issue by Jeeppler** [mercedes-benz/sechub#2056]
# Feature

With #2040 labels can be added in the configuration file. That is a good approach, but as a user of the client it would be beneficial to be able to add labels via the command line. As a result, the labels can be changed by a script (e.g. a CI/CD pipeline) without having to modify the SecHub configuration file.

For example:

~~~
sechub -configfile myconfigfile.json -labels "stage"="testing", "purpose"="quality assurance" scan
~~~

**Comment by sven-dmlr** [comment]
This is already implemented: `-label`
https://mercedes-benz.github.io/sechub/latest/sechub-client.html#commandline-options

And via environment variable `SECHUB_LABELS`
https://mercedes-benz.github.io/sechub/latest/sechub-client.html#environment-variables
