### ISSUE TITLE
Getting started leads to 404 in docs

### ISSUE THREAD

**Issue by masterhanddev** [mercedes-benz/sechub#2090]
The [Getting started](https://mercedes-benz.github.io/sechub/latest/sechub-getting-started.html) link in the [docs](https://mercedes-benz.github.io/sechub/), that apparently got added through #2037, leads currently to a 404 error.
It seems like the page is missing in the docs folder, but there exists an adoc file in the sechub-doc folder already.

**Comment by Jeeppler** [comment]
@masterhanddev thanks for reporting this issue. We are aware of this problem.

In case you want to start from a developer perspective have a look at: https://mercedes-benz.github.io/sechub/latest/sechub-developer-quickstart-guide.html

We will fix the problem of the Getting started guide with the next release.

**Comment by sven-dmlr** [comment]
This is fixed in #2087 
Closing this issue.
