### ISSUE TITLE
Tests inside `ThymeLeafHTMLReportingTest` are green but ouput is empty

### ISSUE THREAD

**Issue by de-jcup** [mercedes-benz/sechub#2125]
## Situation
While developing #2040 and implementing the HTML parts I wanted to test the output and extend tests for it.
`ThymeLeafHTMLReportingTest` was created to test HTML output without starting SecHub server.

But... The output is currently always an empty test - and the tests are still green!

## Wanted
- [x] Fix the problem of the empty html output inside the test results
- [x] Change the tests - add  checks that at least content contains some of the expected vulnerabilities. It shall fail for empty reports..

**Comment by Jeeppler** [comment]
@de-jcup this issue #2071 seems to be related.
