### ISSUE TITLE
Changes on local docs lead to git changes

### ISSUE THREAD

**Issue by de-jcup** [mercedes-benz/sechub#2324]
## Situation
Open `$secHubGitRootFolder/docs/latest/client-download.html` and change someting (simulates a local doc generation) and save the file.

After this , `git status` will give you the information that the file has changed.

Inside  `$secHubGitRootFolder/docs/latest/.gitignore` we have already defined that the folder `latest` (means  `$secHubGitRootFolder/docs/latest/*` shall be ignored... but it does not work.

Reason: Already added files are not handled by git, even mentioned in `.gitignore` !

## Wanted
It shall be possible to generate documentation locally without having any changes on git.

### Variant 1
Reading 
https://stackoverflow.com/questions/1274057/how-do-i-make-git-forget-about-a-file-that-was-tracked-but-is-now-in-gitignore?noredirect=1&lq=1

We could do
```
git rm -r --cached <folder>
```
and remove it from the developer branch.

But... 

> WARNING: While this will not remove the physical file from your local machine, it will remove the files from other developers' machines on their next git pull.

We generate the documentation on every build, so it is not a problem, but the main branch is currently used for documentation to provide github pages - if we would remove this the mentioned way, github pages would not work any longer ?!?

**Comment by sven-dmlr** [comment]
Normal builds do not touch the `docs/latest/` folder.
Only when `./gradlew documentation-with-pages` is called (and there are release tags set).

When doing global replacements, I see no way to prevent that files in `docs/latest/` are changed.
But on release, the documentation is re-built - so even this should do no harm.

summary: I suggest to close this issue
