### ISSUE TITLE
PDS-Solution: Create a PDS solution for PHAN (php SAST)

### ISSUE THREAD

**Issue by de-jcup** [mercedes-benz/sechub#2328]
## Wanted
Implement a PDS solution for PHAN which can be used for PHP SAST scanning
Project site: https://github.com/phan/phan

**Comment by zigfridus** [comment]
@Jeeppler 
Assign me to this issue please.

**Comment by Jeeppler** [comment]
Thanks for taking on the task. I assigned you the issue.

**Comment by zigfridus** [comment]
@Jeeppler 
Sorry for the delay. I would like to ask if this script works fine on your side?
sechub-solutions-shared/scripts/01-test-pds.sh

**Comment by Jeeppler** [comment]
@zigfridus yes, it works fine.

Let's assume you are using the script for GoSec:

~~~
# go into the sechub-pds-solution/gosec folder
# and start the solution
sechub/sechub-pds-solutions/gosec$ ./01-start-single-docker-compose.sh

# make some directory
cd ~
mkdir pds-test-files
# clone a vulnerable app
git clone https://github.com/Jeeppler/vulnerable-go
zip -r vulnerable-go.zip vulnerable-go/

# set the environment variables
export PDS_SERVER=https://localhost:8444
export PDS_USERID=admin
export PDS_APITOKEN="pds-apitoken"
export PDS_PRODUCT_IDENTFIER=PDS_GOSEC

# start the scan
sechub/sechub-solutions-shared/scripts$ ./01-test-pds.sh ~/pds-test-files/vulnerable-go.zip
~~~

For the PHAN solution you only have to change the `PDS_PRODUCT_IDENTFIER`. And you need a different vulnerable app written in PHP.

**Comment by zigfridus** [comment]
@Jeeppler 
I would like to ask whether it is necessary to create other scripts (05, 50 etc) for this issue?

**Comment by Jeeppler** [comment]
@zigfridus I am not sure. Maybe @de-jcup or @sven-dmlr can provider there opinion.

**Comment by sven-dmlr** [comment]
@zigfridus In my opinion you can leave out the 05, 50 etc scripts for now. This can be added later.
