### ISSUE TITLE
SecHub configuration shall not be any longer added to any REST call when unnecessary

### ISSUE THREAD

**Issue by company-jcup** [mercedes-benz/sechub#2366]
## Situation
We have many REST API endpoints where inside the result we have sechub configuration file complete. This could contain sensitive data in future - so not wanted...

## Wanted
The REST calls for job status etc. shall not contain this information any longer.

## Solution
We use this issue as an epic and create dedicated sub issues and link there back

### Sub issues

- #2717
- #2718

**Comment by de-jcup** [comment]
With 

- #3254


the REST endpoints have been cleaned up already. So closing this issue.
