### ISSUE TITLE
Explain authentication for REST API with curl

### ISSUE THREAD

**Issue by de-jcup** [mercedes-benz/sechub#237]
### Situation
At
https://daimler.github.io/sechub/latest/sechub-quickstart-guide.html
we already describe how to connect via curl and credentials.

But at https://daimler.github.io/sechub/latest/sechub-restapi.html we do not have the credential parts explained.

### Solution
We add authentication description into https://daimler.github.io/sechub/latest/sechub-restapi.html

**Comment by Jeeppler** [comment]
Fixed with #1581
