### ISSUE TITLE
Debian 12 Bookworm ca-certificates-java - error: loading java.security file

### ISSUE THREAD

**Issue by Jeeppler** [mercedes-benz/sechub#2384]
# Problem

The bug [ca-certificates-java - Fails to install: Error loading java.security file](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1030129) is fixed and available in testing, but not in Debian 12 Bookworm (stable). We are unable to build our containers using Debian 12 stable.

# Solution

Wait until the fixed `ca-certificates-java` package is available in Debian 12 Bookworm. As long as the fixed `ca-certificates-java` is still in testing, use the testing branch of Debian to build containers. Once it is available switch back to the Debian 12 Bookworm stable release.

**Comment by sven-dmlr** [comment]
Until now, the fix did not make it into Debian 12 Bookworm.
We will use Temurin Java instead of OpenJDK and thus can switch back to Debian 12.
