### ISSUE TITLE
amd64 version of SecHub client 1.0.0 wont work with 20.04.1-Ubuntu

### ISSUE THREAD

**Issue by MichaBub** [mercedes-benz/sechub#2416]
Message:
```
sechub: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by sechub)
sechub: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by sechub)
```

with ubuntu 20 you will only get:
`glibc-source is already the newest version (2.31-0ubuntu9.9).`

P.S.
using linux-386 instead of linux-amd works

**Comment by Jeeppler** [comment]
@sven-dmlr have a look.

**Comment by sven-dmlr** [comment]
Trying to force static builds for all platforms.
