### ISSUE TITLE
Security Enhancement: Use Fixed Commit Hashes for GitHub Actions versions

### ISSUE THREAD

**Issue by Abdullah-Benomar-Shahen** [mercedes-benz/sechub#2665]
### Situation
Some of the used third party GitHub Actions are referenced by their release tags (e.g. actions/useful-action@v1).

### Wanted
For better mitigation against Malicious Code-Injection attacks, it is recommended to pin Third party GitHub Actions to a full Commit SHA (e.g. actions/useful-action@sha255fdvkjfdhgfdg...).
**Reference:**  See [GitHub on this topic](https://docs.github.com/en/enterprise-cloud@latest/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions) 

>**Note**
> I'd like to contribute to the implementation if possible

**Comment by de-jcup** [comment]
Hello @Abdullah-Benomar-Shahen ,

I fully agree with you. The usage of tags for custom/3rdparty GitHub actions is/was a bad idea. We are happy if you would contribute this.

Please do the changes and create a PR for this issue. Thank you.

**Comment by Abdullah-Benomar-Shahen** [comment]
Great, I'll push my changes soon and Create a PR :)

**Comment by Abdullah-Benomar-Shahen** [comment]
Implemented in #2686

**Comment by Abdullah-Benomar-Shahen** [comment]
Implemented in #2686 and merged. Closing this issue.
