### ISSUE TITLE
Note expiry of download link for api-token

### ISSUE THREAD

**Issue by sven-dmlr** [mercedes-benz/sechub#273]
Please note in the notfication email that the link for downloading the api-token expires (after 24 hours).
Ideally tell the exact time/date of the expiry.

---
<sup>Sven Dolderer <sven.dolderer@daimler.com>, Daimler TSS GmbH, [imprint](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sup>

**Comment by haerter-tss** [comment]
Maybe also add an information what the exact username + email address of the technical user is and that you need to use this email address for resetting the api token.

**Comment by zigfridus** [comment]
@Jeeppler 
Please assign me to this issue.

**Comment by zigfridus** [comment]
@sven-dmlr @Jeeppler 
I would like to ask if this value 24 hours is static or could change?

**Comment by zigfridus** [comment]
Hi @sven-dmlr,
thank you for the information.

**Comment by zigfridus** [comment]
Hi @sven-dmlr 

Could you please clarify something for me. 
I found to classes which send notifications about api-tokens:

NewAPITokenAppliedUserNotificationService.java - _Inform user about api token change done_ 
NewApiTokenRequestedUserNotificationService.java - _A notification is send per email to user that a new api token was requested_

In which class would you like to add information about expiration date?

**Comment by sven-dmlr** [comment]
@zigfridus 
This is the one:
NewApiTokenRequestedUserNotificationService.java - _A notification is send per email to user that a new api token was requested_

**Comment by zigfridus** [comment]
@Jeeppler @sven-dmlr 
Please check my [PR](https://github.com/mercedes-benz/sechub/compare/develop...zigfridus:sechub:feature-273-note-expiry-download-link-for-api-token)

**Comment by zigfridus** [comment]
@Jeeppler 
Thank you. I commited your fixes.
Do I have to implement this [proposal](https://github.com/mercedes-benz/sechub/issues/273#issuecomment-1029813382)?

**Comment by Jeeppler** [comment]
@zigfridus here would be my proposal, after I talked with @haerter-tss.

You could include the username into the expiry note:

`The token was created for ${username) and expires at`

for example:

`The token was created for zigfridus and expires at`

including the email address again does not make sense.

**Comment by zigfridus** [comment]
@Jeeppler 
I could try to implement it. But if it isn't necessary I can switch to another issue.

**Comment by Jeeppler** [comment]
@zigfridus it is not essential. I will merge your pull-reuqest. You can switch to another issue.
