### ISSUE TITLE
Handle PDS network access via new SecHub API

### ISSUE THREAD

**Issue by de-jcup** [mercedes-benz/sechub#2734]
## Situtation
With 
- #2731

It becomes possible to download the PDS job information as an sechub administrator.
Before the systemtest framework did directly access the PDS server to fetch the information

## Wanted
It shall be possible to fetch PDS job information by local system tests no matter if localhost or inside private network

## Solution
Use the new API for system tests

**Comment by lorriborri** [comment]
It's not clear how we solve this problem, see Issue #2712
