### ISSUE TITLE
SecHub action workflow

### ISSUE THREAD

**Issue by sarunasr** [mercedes-benz/sechub#2735]
Hello 
I'm using this action: https://github.com/mercedes-benz/sechub/tree/develop/github-actions/scan
and I saw this pull request: https://github.com/mercedes-benz/sechub/pull/2580
I want to ask you which branch/tag we should use in production? I saw this action in the documentation:
`- uses: mercedes-benz/sechub/github-actions/scan@72a27282da80952e6fadcef452c6a9085971c688`
However, using this action I still get warnings about `node12`, I saw that changes were made in the develop branch, so I changed the step to:
`- uses: mercedes-benz/sechub/github-actions/scan@develop` and the warning is gone.
So what action should I use in production? Maybe there is another one?

**Comment by de-jcup** [comment]
The documentation at
https://github.com/mercedes-benz/sechub/blob/develop/github-actions/scan/README.adoc
must be updated.

<sup>We should provide here a hint about the develop branch and a more convenient way.</sup>

**Comment by de-jcup** [comment]
Maybe we should introduce a tag e.g: 

- `github-action-stable`
- `github-action-latest`

**Comment by sven-dmlr** [comment]
@sarunasr 
To sum it up: For now, I recommend to use
`- uses: mercedes-benz/sechub/github-actions/scan@develop`
