### ISSUE TITLE
SecHub Client Support `.bicep`

### ISSUE THREAD

**Issue by Jeeppler** [mercedes-benz/sechub#2736]
# Issue

`.bicep` is not supported by SecHub CLI.

# Wanted

Add `.bicep` to the supported languages in `sechub-cli/script/supported-source-extensions.txt`.

**Comment by raptor-07** [comment]
Does the sechub cli actually support .bicep?
Does this issue expect development of .bicep compatibility within the CLI?

Raising PR if only the .txt file has to be updated nevertheless.

Up for review:

https://github.com/mercedes-benz/sechub/pull/2737
