### ISSUE TITLE
Rest API documentation - infos about authentication missing

### ISSUE THREAD

**Issue by sven-dmlr** [mercedes-benz/sechub#274]
The curl examples in https://daimler.github.io/sechub/latest/sechub-restapi.html don't work. They are rejected by the SecHub server because authentication is missing.

Afaik the authentication works via basic auth (SecHub username / SecHub api token of this user).
This should be added to the documentation.

---
<sup>Sven Dolderer <sven.dolderer@daimler.com>, Daimler TSS GmbH, [imprint](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sup>

**Comment by Jeeppler** [comment]
I think they can be documented using the header option: https://docs.spring.io/spring-restdocs/docs/1.2.6.RELEASE/reference/html5/#documenting-your-api-http-headers

**Comment by Jeeppler** [comment]
Implemented with: #1581
