### ISSUE TITLE
Provide a community branch and describe it inside contributions

### ISSUE THREAD

**Issue by de-jcup** [mercedes-benz/sechub#2759]
## Situation
We have sometimes the situation that we have really good contributions, but we want to test them before finally merging to develop branch. This can be a long running situation which could become become very exhausting for the contributors.

Also it is sometimes a very slow process and could demotivate people.

## Wanted
- For contributors it shall be faster and easier to get their changes merged
- For maintainers it shall be easier to check build and also to be able to make smaller
  changes afterwards before merging it - speed up things

## Solution
- [x] We introduce a `community` branch: https://github.com/mercedes-benz/sechub/tree/community
- [ ] We change documentation at https://github.com/mercedes-benz/sechub/blob/develop/CONTRIBUTING.md accordingly and mention that the PRs shall go to the community branch

**Comment by lorriborri** [comment]
We dropped community branch completely and modified the build action for PRs
