### ISSUE TITLE
[Idea] Ability to increase the severity of specific CWEs to critical

### ISSUE THREAD

**Issue by Jeeppler** [mercedes-benz/sechub#2760]
Introduce the ability on the side of SecHub to increase or set the severity of specific CWEs to critical. For example, the ability to set the [CWE-89 SQL Injection](https://cwe.mitre.org/data/definitions/89.html) to critical.

**Comment by lorriborri** [comment]
We currently rely on the tool output

**Comment by lorriborri** [comment]
We currently rely on the tool output
