### ISSUE TITLE
FindSecurityBugs encounters issues with java 21

### ISSUE THREAD

**Issue by haerter-tss** [mercedes-benz/sechub#2773]
## Situation:
When scanning binaries that use Temurin / Java 21 FindSecurityBugs will fail.

## Solution:
The currently used Spotbugs version does not support Temurin / Java 21. Starting from version 4.8.0 they do. That means that Spotbugs needs to be updated and the system version of the openjdk needs to be updated to 21 too.

**Comment by Jeeppler** [comment]
@haerter-tss it would be nice to have a system test for find security bugs. My idea would be to test FBugs with a number of JVM versions (Java 8, 11, 17 and 21).
