### ISSUE TITLE
Provide possiblity to define header value from file reference

### ISSUE THREAD

**Issue by de-jcup** [mercedes-benz/sechub#2847]
## Situation
The SecHub configuration storage is limited  (see also #2846). If somebody has an extreme big bearer token (for any reasons) it can lead to the situation that a webscan job cannot be created.

Header tokens can be defined as any other header information, see
https://mercedes-benz.github.io/sechub/latest/sechub-restapi.html#sechub-config-example-webscan-header

An example:
```json
{
  "apiVersion" : "1.0",
  "webScan" : {
    "url" : "https://productfailure.demo.example.org",
    "headers" : [ {
      "name" : "Authorization", 
      "value" : "{{ .HEADER_VALUE }}" 
    }
    ]
  }
}
```
## Wanted
It shall be possible to provide even very bigger header content

## Solution
To provide even bigger header content, it shall be possible to reference a file as content for the header value. Means the big data is inside the S3 or NFS storage.

We provide this with already exist `use` approach inside the configuration file, means it is an array as any other use-reference, but we do only allow one entry (and one entry is also mandatory and must be contained inside the data section)

### Example
```json
{
  "apiVersion" : "1.0",

   "data" : {
    "sources" : [ {
      "name" : "initial-bearer-token", 
      "fileSystem" : {
        "files" : [ "gamechanger-webapp/build/gen/inial-bearer-token.txt" ]
      }
    }
    ]
  },

  "webScan" : {
    "url" : "https://productfailure.demo.example.org",
    "headers" : [ {
      "name" : "Authorization", 
      "use" : [ "initial-bearer-token" ]
    }
    ]
  }
}
```

**Comment by winzj** [comment]
The `SecHubConfigurationModelValidator` should return an error if both `value` and `use` is used for the same header at the same time. This means the following shall not be allowed for headers:
```json
{
  "apiVersion" : "1.0",

   "data" : {
    "sources" : [ {
      "name" : "initial-bearer-token", 
      "fileSystem" : {
        "files" : [ "gamechanger-webapp/build/gen/inial-bearer-token.txt" ]
      }
    }
    ]
  },

  "webScan" : {
    "url" : "https://productfailure.demo.example.org",
    "headers" : [ {
      "name" : "Authorization",
      "value" : "{{ .HEADER_VALUE }}",
      "use" : [ "initial-bearer-token" ]
    }
    ]
  }
}
```
