### ISSUE TITLE
Changes on new HTML report

### ISSUE THREAD

**Issue by de-jcup** [mercedes-benz/sechub#2898]
## Situation
Currently (not in develop branch)
we have folloiwng situation inside `fragement-web-scan-table.html` 

```html
<!-- /* 
Called by fragments-detail.html

parameters:
  - findingEntry: currently a map table entry (key/value) 
     key = name of finding, used to group same findings (e.g. "Command injection" as headline, but 5 findings for this
     value= List<SecHubFinding> findings
 */ -->
<th:block th:fragment="scanTable">
  <!--... -->
  <details th:with="webRequest=${findingEntry.value[0].web.request
  <!--... -->
```

Means: only the first SecHub finding for the group (finding name) is rendered in the detail HTML report.

## Wanted
Clarify if this exactly what is wanted.

## Solution
We will change the report look and feel - see last comment

**Comment by de-jcup** [comment]
The report grouping and only showing one entry looks rendered this way
![image](https://github.com/mercedes-benz/sechub/assets/11644753/921dceaa-d555-4ed0-932c-fa1ca1a939ef)

Means "Open details" is the point where only one entry is rendered (one detail). 

[report-examples.zip](https://github.com/mercedes-benz/sechub/files/14239085/report-examples.zip)

**Comment by winzj** [comment]
For comparison, the old report looked like this:
![image](https://github.com/mercedes-benz/sechub/assets/86345915/e1551353-b59b-463d-9c49-a1481a27de13)

**Comment by de-jcup** [comment]
We discussed in core team.

1. We want no loss of information inside the reports
2. The overview is nice, but we want it at the beginning as details
3. We still want the IDs inside the HTML report
4. We want the IDs linked inside

Here a short hand sketch:
![image](https://github.com/mercedes-benz/sechub/assets/11644753/f9b7cfc2-aeb4-4b77-8397-a1088c3445ed)
