### ISSUE TITLE
Add username to 401 Unauthorized log message

### ISSUE THREAD

**Issue by haerter-tss** [mercedes-benz/sechub#2907]
# Situation
If someone tries to access SecHub with a wrong user and / or wrong API token a log message of the type "WRONG_USAGE" and "401 UNAUTHORIZED" is created. Missing in this message is the name of the user that was tried. This would be helpful for various troubleshooting scenarios.

Example:

![image](https://github.com/mercedes-benz/sechub/assets/98736006/b97a514a-73c8-4054-b610-b3b67bd3d949)

# Wanted
The user name should be added to the log messages 

# Solution
- Implement extraction for basic auth user
- add to security log data

## Extraction
- returns `info.no-basic-auth-defined` when not basic auth info available (e.g. when anonymous)
- returns `error.unsupported-format` when its not a basic auth information
- returns `error.too-small` when "Basic" found inside authorization header, but not long enough
- returns `error.colon-count-wrong:$colon`
- returns $username from basic auth otherwise - when empty username, the return value is empty

**Comment by de-jcup** [comment]
Here some example outputs from last commit (its now also sorted, see #2928 )

# Illegal anonymous access
```
data=
{
  "afterSessionClosed" : true,
  "basicAuthUser" : "info.no-basic-auth-defined",
  "clientIp" : "127.0.0.1",
  "httpHeaders" : {
    "accept" : "*/*",
    "host" : "localhost:8443",
    "user-agent" : "curl/7.81.0"
  },
  "message" : "401 UNAUTHORIZED",
  "method" : "GET",
  "requestURI" : "/api/admin/i-do-not-exist",
  "sessionId" : "92CF851EXAMPLE962F548E636A7",
  "type" : "WRONG_USAGE"
}
, message=401 UNAUTHORIZED
```

```
2024-02-23 09:17:51.208  WARN 11987 --- [0.1-8443-exec-9] c.m.s.s.l.DefaultSecurityLogService      : [SECURITY] [POTENTIAL INTRUSION]:
data=
{
  "afterSessionClosed" : true,
  "basicAuthUser" : "int-test_superadmin",
  "clientIp" : "127.0.0.1",
  "httpHeaders" : {
    "accept" : "image/avif,image/webp,*/*",
    "accept-encoding" : "gzip, deflate, br",
    "accept-language" : "en-US,en;q=0.5",
    "authorization" : "Basic aW***length:66",
    "connection" : "keep-alive",
    "cookie" : "JSESSIONID=C35C83EXAMPLEB50EB6E3FA",
    "host" : "localhost:8443",
    "referer" : "https://localhost:8443/xyz",
    "sec-fetch-dest" : "image",
    "sec-fetch-mode" : "no-cors",
    "sec-fetch-site" : "cross-site",
    "user-agent" : "Mozilla/5.0 (X11; Linux x86_64; rv:123.0) Gecko/20100101 Firefox/123.0"
  },
  "message" : "403 FORBIDDEN",
  "method" : "GET",
  "requestURI" : "/xyz",
  "sessionId" : "5F5DBCF6EXAMPLED4B4BE1F547",
  "type" : "POTENTIAL_INTRUSION"
}
, message=403 FORBIDDEN
```
