### ISSUE TITLE
Add blacklist for errors

### ISSUE THREAD

**Issue by ghost** [mercedes-benz/sechub#291]
Sometimes the static code analysis detects problems that are solved somewhere else.
It would be great to somehow exclude such a specific error, so it doesn't show up on every run of the tool.

---
<sup>Till Hoffmann <[till.hoffmann@daimler.com](mailto:till.hoffmann@daimler.com)> Daimler TSS GmbH. [Imprint](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sup>

**Comment by sven-dmlr** [comment]
This should be covered by defining false-positives which was introduced in late 2020.

Docs link: https://mercedes-benz.github.io/sechub/latest/sechub-client.html#section-client-false-positives-mark (scroll down for interactive mark/unmark)
