### ISSUE TITLE
Issue in github action documentation

### ISSUE THREAD

**Issue by haerter-tss** [mercedes-benz/sechub#3140]
## Situation
The github action [documentation](https://github.com/mercedes-benz/sechub/blob/develop/github-actions/scan/README.adoc) mentions that multiple scan types can be used. It says you should define it like this: `scan-types: codeScan, secretScan`

It seems like this is incorrect and no matter in which order multiple scan-types are defined, only a codeScan is executed which suggests that it falls back to the default 

## Wanted
The documentation should be edited with the correct syntax.

## Solution
When the blank between the multiple scan-types is removed everything works as expected:  `scan-types: codeScan,secretScan` so it should be removed from the documentation. All other examples use apostrophes so for a continious design I suggest that  this is also put in apostrophes:
`scan-types: 'codeScan,secretScan'`

**Comment by sven-dmlr** [comment]
This has been addressed in #3143 
-> closing this issue
