### ISSUE TITLE
Transfer PDS_STORAGE variables to prepare wrapper application

### ISSUE THREAD

**Issue by lorriborri** [mercedes-benz/sechub#3176]
## Situaton
The prepare wrapper application needs access to variables defined in `PDSStorageConstants` because it needs access to the shared storage to upload remote data. 

## Wanted
`PDSExecutionCallable` should put the PDS_STORAGE variables as environment variables to the process builder, but only when PREPARE is the Scantype

## Solution
Implement a component that only hosts the PDS_STORAGE variables and has a function `createStorageMap` to create a map of all PDS_STORAGE variables. The `PDSExecutionEnvironmentService` should autowire the component and call the `createStorageMap` function and add the PDS_STORAGE variables to the return map, when the ScanType is PREPARE.

**Comment by de-jcup** [comment]
When I created and implemented #3142 I had the idea to handle it different for scan type PREPARE. But I decided to NOT do this. 

Main reasons were:
- avoid magic for special scan types, treat every scan type as same citizen...
- be future ready. if we need any other special env variable at runtime for a PDS solution, we just enter it again
- The script processes shall not have access to other environment variables than necessary.
- It shall be clear which environment variables are accessible by script and it shall be configurable

#3142 is already implemented and merged to develop branch and works.
IMO we should close this issue.
