### ISSUE TITLE
Implement caching for GitHub Actions client download

### ISSUE THREAD

**Issue by hamidonos** [mercedes-benz/sechub#3199]
## Situation
Currently the client (20mb) is downloaded every time the build pipeline runs because no caching is implemented.

## Wanted
- The client is cached by its version.
   For example: 1.6.1 is only downloaded once for every run

- Also the download should be logged properly so that the client knows that something is happening.
   Log the client version that is downloaded and progress etc.

**Comment by sven-dmlr** [comment]
Client caching is implemented -> closing this issue
