### ISSUE TITLE
Handle empty source uploads in dedicated way

### ISSUE THREAD

**Issue by de-jcup** [mercedes-benz/sechub#32]
Checkmarx adapter does currently fail when source files are empty.

E.g. : 
```
Caused by: com.daimler.sechub.adapter.AdapterException: __[SECHUB-UID:18b606d1-6729-486f-83d1-50ea0c7634ed]__ CheckmarxAdapterV1:The queuing has failed:Failed to start scanning due to one of following reasons: source folder is empty, all source files are of an unsupported language or file format
```
On response we got only one finding with text:
"description" : "Security product 'CHECKMARX' failed, so cannot give a correct answer.",

We could handle this in future in one of the following variants:

1. Show a dedicated finding (warning) that no sources where uploaded 
    and do not call any product . So no matter which product this would be always same.
2. Let it as is - means being product specific response.... not nice
3. SecHub accepts this always as "green" - no source, no cry...
So no matter which product this would be always same.

**Comment by Jeeppler** [comment]
@de-jcup Is this still an issue?

**Comment by de-jcup** [comment]
Yes - it is still an issue.

As discussed in our team we will handle at `SecHub` side the empty source code uploads by inspecting the multipart file size:
When we have <= 22 bytes of length of source code zip file, the file is empty
(see https://en.wikipedia.org/wiki/ZIP_(file_format)#Limits) .

In this case the REST API for the upload will fail with HTTP code 400 (bad request).

**Comment by sven-dmlr** [comment]
22 bytes is the smallest possible size for a zip file.

Although it is possible to create a bigger zip file e.g. >2000 bytes with no files inside but only folders:
```bash
> mkdir -p empty/empty/empty/empty/empty/empty/empty/empty/empty/empty/empty/

> zip -r empty.zip empty
  adding: empty/ (stored 0%)
  adding: empty/empty/ (stored 0%)
  adding: empty/empty/empty/ (stored 0%)
  adding: empty/empty/empty/empty/ (stored 0%)
  adding: empty/empty/empty/empty/empty/ (stored 0%)
  adding: empty/empty/empty/empty/empty/empty/ (stored 0%)
  adding: empty/empty/empty/empty/empty/empty/empty/ (stored 0%)
  adding: empty/empty/empty/empty/empty/empty/empty/empty/ (stored 0%)
  adding: empty/empty/empty/empty/empty/empty/empty/empty/empty/ (stored 0%)
  adding: empty/empty/empty/empty/empty/empty/empty/empty/empty/empty/ (stored 0%)
  adding: empty/empty/empty/empty/empty/empty/empty/empty/empty/empty/empty/ (stored 0%)

> ls -al empty.zip
-rw-r--r-- 1 myuser mygroup 2222 Nov 11 17:23 empty.zip
```

-> So the zip file's size cannot help to determine if it contains regular files or not.
The only way I can think of is to list the zip file's content.

**Comment by de-jcup** [comment]
@sven-dmlr 
- I do not want to unpack the zip files while uploading to SecHub
- This is a just a short upload stop when we have really an empty file
- The sechub client does (AFAIK) not add empty folders
- #1744 will do the inspection at PDS side - here we will have the unpacking etc. available and will handle such problems in detail

So I think the quickwin implementation here is a good first step, but logic about the data shall be at PDS side.

**Comment by sven-dmlr** [comment]
When the SecHub client is used, then no empty .zip file (no regular files) will be uploaded:
```
> sechub scan
 _____           _   _       _
/  ___|         | | | |     | |
\ `--.  ___  ___| |_| |_   _| |__
 `--. \/ _ \/ __|  _  | | | | '_ \
/\__/ /  __/ (__| | | | |_| | |_) |
\____/ \___|\___\_| |_/\__,_|_.__/ Client Version 0.31.0-20220602125019

2022-11-14 09:56:35 (+01:00) Zipping folder: empty (/home/myuser/tmp/example/empty)
2022-11-14 09:56:35 (+01:00) ERROR: Zipfile has no content!
Exiting due to fatal error while creating sources zip file...
```
