### ISSUE TITLE
Provide a Dockerfile to build the container image of sechub server

### ISSUE THREAD

**Issue by damelo** [mercedes-benz/sechub#320]
Greetings, 

Sechub could run in a Kubernetes cluster to allow elasticity and a continuous deployment approach.

Regards,

**Comment by de-jcup** [comment]
Hello @damelo , 

you are right - `SecHub` is explicit designed to run on Kubernetes cluster or inside docker compose etc.. At the moment we provide only some hints about Kubernetes setup inside documentation (see https://daimler.github.io/sechub/latest/sechub-operations.html#kubernetes ) but maybe we should provide some default setup.

Would you like to have a docker file inside the sechub git repository (e.g. under `sechub-kubernetes`)  or would you prefer a sechub container ready to go inside a public container registry (e.g. https://hub.docker.com/ ) ?

---
<sup>Albert Tregnaghi <albert.tregnaghi@daimler.com>, Daimler TSS GmbH, [imprint](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sup>

**Comment by de-jcup** [comment]
Instead of https://hub.docker.com we could provide the docker/podman images also **by GitHub packages,** as described at 
https://docs.github.com/en/packages/using-github-packages-with-your-projects-ecosystem/configuring-docker-for-use-with-github-packages

**Comment by Jeeppler** [comment]
We will provide a Dockerfile and a Helm chart.

This is a larger topic, as a result we convert this to an epic.

**Comment by sven-dmlr** [comment]
Closing due to all subtasks are closed
