### ISSUE TITLE
Update version inside package.json for GitHub Action to 2.1.0

### ISSUE THREAD

**Issue by hamidonos** [mercedes-benz/sechub#3200]
## Wanted
- GitHub Action package.json should have the version 2.1.0
[github-actions/scan/package.json](https://github.com/mercedes-benz/sechub/blob/d6ff37483ed828e6062c2b76ea96db9cbd6e6070/github-actions/scan/package.json)

**Comment by sven-dmlr** [comment]
Will be done in #3202 for each release.
So closing this issue.
