### ISSUE TITLE
SecHub Server start, allow some config parts only as ENV variables

### ISSUE THREAD

**Issue by de-jcup** [mercedes-benz/sechub#3224]
## Situation
(This is related to #3223 ) but here we only focus on the security part.

We do not want to have the possibility that any tool on the SecHub machine would accidently store any sensitive data by event logs.

## Wanted
Sensitive information may be not be defined with something else than environment variables

### SecHub Solution
- [x] sechub solution run.sh script shall not use system properties for startup but only env variables

### Java
- [ ] Server startup shall check that sensitive information is only available via env env variables

Sensitive information are
- `spring.datasource.password`
- `sechub.initialadmin.userid`
- `sechub.initialadmin.apitoken`
- `sechub.initialadmin.email`
- `sechub.storage.*`

**Comment by sven-dmlr** [comment]
Feature branch is created: `feature-3224-server-force-some-settings-as-env-vars`
