### ISSUE TITLE
Correct Prepare Wrapper version in dockerfile

### ISSUE THREAD

**Issue by haerter-tss** [mercedes-benz/sechub#3302]
### Situation:
In the Dockerfile sechub-pds-solutions/prepare/docker/Prepare-Debian.dockerfile the version of the pds wrapper is given as 0.0.0. It should be 1.0.0

### Solution:
Change the variable to 1.0.0

**Comment by sven-dmlr** [comment]
As discussed: The wrapper version should only be defined in one place: `env`
Will implement this.
