### ISSUE TITLE
There's a `build.gradle` file committed as part of the server core's Java source set

### ISSUE THREAD

**Issue by sschuberth** [mercedes-benz/sechub#3397]
While doing a compliance scan with [ORT](https://github.com/oss-review-toolkit/ort) on this repository, it occurred to me that there is a `build.gradle` committed at an unusual location:

https://github.com/mercedes-benz/sechub/blob/develop/sechub-server-core/src/main/java/com/mercedesbenz/sechub/server/core/build.gradle

Just to double-check: Is this Gradle build file really supposed to be committed as part of the Java source set?

**Comment by schr3gl3j** [comment]
@de-jcup could you answer this?

**Comment by winzj** [comment]
@sschuberth @schr3gl3j I am currently trying to find out if this `build.gradle` file is even necessary for the build to complete. I will close this issue with #3398 if it is not necessary

**Comment by sschuberth** [comment]
Thanks for checking @winzj. At least that project does not show up with

    ./gradlew -q projects | grep sechub-server-core

so it appears to be unused to me.
