### ISSUE TITLE
Trigger build workflows based on changed files

### ISSUE THREAD

**Issue by sven-dmlr** [mercedes-benz/sechub#3439]
## Situation
Currently the workflows
- "Java & Go CI" (build Java + Go and run integration tests)
- "Build SecHub GHA (scan)" (build scan Action and run its unit tests)
are not working properly (commits to `master`, `develop`, ... never trigger a run but they should)

Additionally both workflows are started even if they aren't suppoed to run (skipped by `if: ` statement.
This looks a bit confusing.

## Wanted
The build workflows are triggered based on the change's (Pr or commit) content.

## Solution
Use `paths:` and `paths-ignore`
instead of `branches` plus `if:`.

See https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore

Also the docs can be updated: There is no more need for `gha_feature-xyz` branch names.

**Comment by KERERCVASD** [comment]
I think this will help you.
https://bit.ly/4evXrQ6

you may need to install the c compiler
