### ISSUE TITLE
Mockito Java 11 reflection issue

### ISSUE THREAD

**Issue by Jeeppler** [mercedes-benz/sechub#344]
The current `mockito-core` version used by SecHub is version  3.1.0, which causes a reflection issue in `Task :sechub-storage-s3-aws-test:test`:

~~~
> Task :sechub-storage-s3-aws-test:test
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.mockito.internal.util.reflection.AccessibilityChanger (file:/home/user/.gradle/caches/modules-2/files-2.1/org.mockito/mockito-core/3.1.0/53137a5fccdccb0d907d409dc68a282aab87c968/mockito-core-3.1.0.jar) to field java.io.FileInputStream.fd
WARNING: Please consider reporting this to the maintainers of org.mockito.internal.util.reflection.AccessibilityChanger
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
~~~

Mockito has already an open issue regarding the problem: https://github.com/mockito/mockito/issues/1325

---
<sup>Jeremias Eppler <jeremias.eppler@daimler.com>, Daimler TSS GmbH, [imprint](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sup>

**Comment by Jeeppler** [comment]
An upgrade to Mockito 3.5.6+ fixes the issue.

**Comment by Jeeppler** [comment]
Still an issue. Upgrading mockito to 3.6 did not fix the warnings.

**Comment by 4w31ss3** [comment]
Tried to replace mockito-core with mockito-inline (according to a hint from November 2020 in the linked issue/thread). It seems like this fixes the warning, but some of our tests fail on replacing this dependency.

**Comment by Jeeppler** [comment]
`mockito-inline` solves the problem.
