### ISSUE TITLE
SecHub Windows Client Includes Zip File in Compression, Causing Endless Loop

### ISSUE THREAD

**Issue by haerter-tss** [mercedes-benz/sechub#3447]
### Situation
When doing a scan for secrets ("secretScan") the SecHub client compresses source code into a zip file. When including "." (the folder you are currently in), the SecHub Linux client successfully excludes the zip file from the compression and works as expected. However, when performing the same action with the Windows SecHub client, the zip file itself is included in the compression, resulting in an endless loop.

Example sechub.json:
```json
{
  "apiVersion": "1.0",
  "secretScan": { "use": [ "myscan" ] },
  "data": {
    "sources": [
      {
        "name": "myscan",
        "fileSystem": { "folders": [ "." ] }
      }
    ]
  }
}
```

### Wanted
It is desired that this bug is investigated and fixed. 

### Solution
A potential solution could involve checking if the exclude pattern does not work on Windows for some reason. Alternatively, it might be that the temporary zip file on Windows has a different name or extension.

**Comment by sven-dmlr** [comment]
The problem applies only to scan type "secretScan".
