### ISSUE TITLE
Sechub is not allowed in MB MacBook

### ISSUE THREAD

**Issue by zshareef** [mercedes-benz/sechub#3577]
Dear Colleagues,

I have recently upgraded my MacBook to new Mac Service in Mercedes-Benz.
When I try to execute the binary of "sechub" as per recommendation, I am getting an error that 'sechub' cannot be executed because it is not sure that is it a malware or not.

In System Settings --> Privacy and Security, I have clicked on "Allow Anyway" but it is not taking any action and it is still blocked.

I talked to my support and according to them "sechub has to change the package".

Could you please support me in this issue. I hope that many colleagues are using MacBook for development and they will encounter the same issue.

Thanks

**Comment by haerter-tss** [comment]
Hi @zshareef 

Thank you for bringing this issue to our attention. I have a solution for the problem you're experiencing on MacOS:

Please open up a terminal and change into the directory where the SecHub client is located. Then type in the following command: `xattr -c ./sechub`
This removes all extendend attributes from the client which results in MacOS being able to run it.

However, I noticed that your issue contains internal information, such as internal links and mentions of Mercedes-Benz. For security and confidentiality reasons, please remove any internal information from the issue. In the future, kindly avoid including such details in public repositories.

Thank you for your understanding and cooperation.

Best regards,
Rouven

**Comment by haerter-tss** [comment]
As we haven't received any further updates or responses in over a month, we are closing this issue for now. If you have any additional questions or need further assistance, please feel free to reopen the issue or create a new one.

Thank you for your understanding and cooperation.
