### ISSUE TITLE
Scheduler start should be aware of version

### ISSUE THREAD

**Issue by de-jcup** [mercedes-benz/sechub#389]
### Kubernetes - one deployment for sechub-server
Example with Kubernetes:

Let us assume we have deployed old server version 0.17.2 and want to do a rolling update to 0.18.0.
And let assume we have only ONE deployment.yaml and we do this by script - e.g. bash

#### What happens?
1. script stops scheduler execution per API
2. script triggers k8s update of deployment
3. script starts scheduler execution per API

Then we could have following situation (example is with 3 PODs):

```
POD 1: version 0.17.2 terminating
POD 2: version 0.17.2 running
POD 3:version 0.18.0 running
POD 4:version 0.18.0 starting
POD 5: version 0.18.0 container creating
```

So ... scheduler will be activated on POD2 as well and next Job request could be done in POD2!

When POD 5 is alive POD 2 will be terminated by k8s and ... we got a zombie job which must be restarted by admins manually.

## Solution
stop scheduler REST API is kept as is and will work for all running server versions
(re-start) scheduler REST API shall have an **optional** parameter "server-version".

So on a rolling update the script will do a POST to
https://sechub.example.com/api/admin/scheduler/enable/job-processing with post parameter "server-version=0.18.0".

Attention: 0.17.2 does not have this feature, neither have it 0.18.0 - but in future this could be implemented, so these explicit server versions are just fiction at the moment!

The server with 
- 0.17.2 receives the "enable scheduler action" - it looks for its own version in global configuration db entry, see the difference and just ignores. 
- 0.18.0 will receive the "enable scheduler action" - and update scheduler state in DB and stores server-version as configuration entry.

After enabling the server will periodically check for enabled state by looking in scheduler status. The scheduler state will now contain server version and server will check again this.

So 
- 0.17.2 server will still stop processing because start has not been enabled for its version
- 0.18.0 server will start processing again

k8s will destroy old POD after a while but we have no longer zombie processes

---
<sup>Albert Tregnaghi <albert.tregnaghi@daimler.com>, Daimler TSS GmbH, [imprint](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sup>

**Comment by winzj** [comment]
We will not implement this, because in #390 we now provide scheduler stop in SIGERM instead which prevents this.
