### ISSUE TITLE
Upgrade gradle v7 + Upgrade to new gradle configurations

### ISSUE THREAD

**Issue by de-jcup** [mercedes-benz/sechub#433]
When Gradle 7 is available we should upgrade to this version.

Before we can do this, we have following ToDos:
 - Currently we use "compile", "testCompile" etc.
   This is deprecated and will no longer be supported with Gradle 7.

**Comment by sven-dmlr** [comment]
Meanwhile we are using gradle 7.5

No "compile" or "testCompile" found in *.gradle files. So all looks fine.

Closing this issue.
