### ISSUE TITLE
Usecase: lists projects with data

### ISSUE THREAD

**Issue by Jeeppler** [mercedes-benz/sechub#456]
## Situation
There exists no API call for a user, owner or admin to get a list of his assigned projects.

## Wanted 
The user should be able to list all projects one is assigned to.

For example, user Alice has access to three projects:

- inventory_app
- store_managment
- crm_app

Alice should be able to list all projects she has access to, as well as the name of the owner of the projects.

If Alice is the owner of a project, she should be able to see the userID of all assigned users.

If Alice is an Admin, she gets all information about assigned projects.

## Solutions
- implement new Rest Controller
- implement Service to get List of projects
- response should be JSON Array

**Comment by sven-dmlr** [comment]
Good idea!
I'll add the "server" label. Once implemented on the server, it will be implemented on client side.

**Comment by Jeeppler** [comment]
Similar to: #928. To get some understanding on how to implement it have a look at pull-request #1790.

Similar to [UC 14](https://mercedes-benz.github.io/sechub/latest/sechub-architecture.html#section-usecase-UC_014) and [UC 71](https://mercedes-benz.github.io/sechub/latest/sechub-architecture.html#section-usecase-UC_071).
