### ISSUE TITLE
401 if there are dashes in username

### ISSUE THREAD

**Issue by Gadzhi13** [mercedes-benz/sechub#463]
One of the users with dashes in the username was constantly gettting 401 responses. After recreating the same user without dashes the user got through.

---
<sup>Gadzhi Abdurazakov <gadzhi.abdurazakov@daimler.com>, Daimler TSS GmbH, [imprint](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sup>

**Comment by sven-dmlr** [comment]
Added "server" label.

-> Please check, if this is a wanted behaviour or an issue on the server.

**Comment by Jeeppler** [comment]
@sven-dmlr @haerter-tss is this still relevant?

**Comment by sven-dmlr** [comment]
I did a test: User IDs containing `-` as well as `_` are working.
Closing this issue.
