### ISSUE TITLE
Client: Make temporary directory configurable

### ISSUE THREAD

**Issue by romahnp** [mercedes-benz/sechub#467]
## client: Scan action will store zip on disk which may cause permission denied
At the moment the "code scan" action zips the code-folder before the upload. If the current user doesn't have write access to this directory (e.g. in a CI context) the check will fail because of a permission denied error. 

We suggest three possible solutions: 
- Zipping to "temp" directory
- Zipping file without writing to disk
- Create parameter to configure Zip output directory

---
<sup>Paul Romahn <paul.romahn@daimler.com>, Daimler TSS GmbH,  [imprint](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sup>

**Comment by Jeeppler** [comment]
@romahnp thanks for opening the issue.

**Comment by sven-dmlr** [comment]
Will introduce a `-tempdir` option.
There all temporary files (currently only .zip file) will be created.
Default is current directory. (compatibility with current behaviour)
