### ISSUE TITLE
Replace usecase "Admin checks server version" with "Admin fetches server runtime data" and provide JSON object

### ISSUE THREAD

**Issue by Jeeppler** [mercedes-benz/sechub#469]
The admin checks server version API returns a plain text result instead of the usual JSON: https://daimler.github.io/sechub/latest/sechub-restapi.html#admin-checks-server-version

The problem with that is, that OpenAPI cannot figure out the type of the returned payload.

---
<sup>Jeremias Eppler <jeremias.eppler@daimler.com>, Daimler TSS GmbH, [imprint](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sup>

**Comment by Jeeppler** [comment]
Related #377

**Comment by de-jcup** [comment]
We will do following changes here

- [ ] Introduce `ServerRuntimeData` as Json object which will initially hold `serverVersion` inside, but can be extended for future needs.
- [ ] Change url from `/api/admin/info/version` to `/api/admin/info/server`
- [ ] Rename usecase `@UseCaseAdminChecksServerVersion` to `@UseCaseAdminFetchesServerRuntimeData`
- [ ] Update the URL builder (TestAPI)
- [ ] Update the parse mechanism inside `sechub-api.sh` / `admin-api.sh`

**Comment by de-jcup** [comment]
I marked this issue with a "breaking-change" label (because the REST API changed a bit) . But it is only a real breaking change, if somebody has automated administrative parts by their own. We provide and maintain `admin-api.sh` by our own - so it is not really a breaking change.
