### ISSUE TITLE
Publish build artifacts to github packages when tagged

### ISSUE THREAD

**Issue by de-jcup** [mercedes-benz/sechub#482]
We want to publish build artifacts (client, sechub server, pds server) to github packages - when corresponding git tags are set (e.g. v0.23.0-client, v0.21.0-server etc.)

Here some additional links

- We should use GITHUB_TOKEN as described at https://docs.github.com/en/free-pro-team@latest/actions/reference/authentication-in-a-workflow 
- gradle usage is described at https://docs.github.com/en/free-pro-team@latest/packages/guides/configuring-gradle-for-use-with-github-packages
- Create release: https://github.com/actions/create-release
- Upload assets to release: https://github.com/actions/upload-release-asset

---
<sup>Albert Tregnaghi <albert.tregnaghi@daimler.com>, Daimler TSS GmbH, [imprint](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sup>

**Comment by Jeeppler** [comment]
@sven-dmlr can this be closed in your opinion?
