### ISSUE TITLE
Improve documentation branch - divide images + version locations

### ISSUE THREAD

**Issue by de-jcup** [mercedes-benz/sechub#540]
## Situation
Currently we got only one `latest` for all at https://daimler.github.io/sechub/

## Wanted
As a developer I want to update server documentation for a dedicated server without influencing PDS or SecHub client - e.g. when code base for those releases differ.

## Solution

We must differ between
- SecHub Client 
- SecHub Server
- PDS

So we need 3 different directories at 
https://github.com/Daimler/sechub/tree/documentation/docs/latest

e.g.
https://github.com/Daimler/sechub/tree/documentation/docs/latest/sechub-client
https://github.com/Daimler/sechub/tree/documentation/docs/latest/sechub-server
https://github.com/Daimler/sechub/tree/documentation/docs/latest/pds

## Optional
Maybe it is possible to integrate the documentation upload directly into the release build by github actions (but be aware about the draft releases!)

**Comment by sven-dmlr** [comment]
@de-jcup 
_As a developer I want to update server documentation for a dedicated server without influencing PDS or SecHub client - e.g. when code base for those releases differ._

This is basically implemented with #984.

Although the split into several subfolders is not done. Do we need this? What is the benefit?
With HTML, common images can easily be shared. This would be more complex when having subfolders.

I propose to close this issue... :-)

**Comment by sven-dmlr** [comment]
Closing this issue. (If appropriate: please create a new one)
