### ISSUE TITLE
Client: getStatus / getReport default to "latest" (without job-UUID)

### ISSUE THREAD

**Issue by superlars1337** [mercedes-benz/sechub#545]
### Problem
client requires a UUID to get the report
We are running SecHub each night in an automated pipeline - and I want to check the latest results on my laptop.
Therefore I have to find the current uuid in the pipeline report...

### Solution
deliver "latest" report when no uuid is given -or- define uuid "latest" which points to the latest report
this will save a lot of time and makes it more userfriendly

### Impact commands
- getStatus
- getReport

Depends on #928

**Comment by Jeeppler** [comment]
See: #366

**Comment by sven-dmlr** [comment]
Good idea! :+1: 
Created #928 for implementation on server side.
Once it is implemented, the client can be extended to default to "latest" if no SecHub job UUID is provided.
