### ISSUE TITLE
Support includes and excludes in DAST

### ISSUE THREAD

**Issue by Jeeppler** [mercedes-benz/sechub#568]
At the moment one can provide a number of [URIs to scan](https://daimler.github.io/sechub/latest/sechub-restapi.html#uris) via DAST. Those URIs have to be whitelisted. However, one might want to scan specific pages below the URIs.

The URI to scan:

```
  "webScan"  : {
      "uris": ["https://www.gamechanger.example.org"]
  }
```

Pages which should be included:

```
  "webScan"  : {
      "uris": ["https://www.gamechanger.example.org"],
      "include": [
            "https://www.gamechanger.example.org/home", 
            "https://www.gamechanger.example.org/dashboard", 
            "https://www.gamechanger.example.org/dashboard/#/exampleView"
      ]
  }
```
Those includes are helpful in case a page cannot be detected via crawling or spidering. OWASP ZAP as well as Netsparker support an `include` feature. Both not only support static includes, but includes can be regular expressions. For example:

```
  "webScan"  : {
      "uris": ["https://www.gamechanger.example.org"],
      "includes": [
            "https://www.gamechanger.example.org/home", 
            "https://www.gamechanger.example.org/dashboard/.*"
      ]
  }
```

In the above example, all pages under `dashboard/.*` would be included. Meaning `dashboard/view1`, `dashboard/view2` etc.

However, using regular expressions for excludes is more useful. For example:

```
  "webScan"  : {
      "uris": ["https://www.gamechanger.example.org"],
      "excludes": [
            "https://www.gamechanger.example.org/admin/.*", 
            "*secret*",
      ]
  }
```

In this example, the all admin pages and all pages which have `secret` in their name will be excluded from the scan.

The includes are particularly helpful while scanning single applications, where the crawler has difficulties finding a page. Consider the following, the `https://www.gamechanger.example.org/dashboard` page contains a clickable `div` element which opens `https://www.gamechanger.example.org/dashboard/#/exampleView`. The link is made clickable by some [unobtrusive JavaScript](https://en.wikipedia.org/wiki/Unobtrusive_JavaScript) code:

```
<script>
window.addEventListener('load', function() {
  let button= document.querySelector("div");
  button.addEventListener("click", function() { location.hash = "#/exampleView"; }, false);
});

// this code is simplified and might not work
window.addEventListener('hashchange', function() { openView(location.hash);  }, false);
</script>

…

<body>
  <div>Open Example View</div>
</body>
```

For a crawler to figure out, that the "div" will have a "click" event attached, which changes the location hash and opens a new view based on the location hash, is difficult. However, by directly accessing the `https://www.gamechanger.example.org/dashboard/#/exampleView` the example view can be opened and the DAST tool can try to find vulnerabilities.

---
<sup>Jeremias Eppler <jeremias.eppler@daimler.com>, Daimler TSS GmbH, [imprint](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sup>

**Comment by manu-ki** [comment]
list all excluded sites in the report, too

**Comment by de-jcup** [comment]
> Please, list all excluded sites in the report, too (as metadata)
> 
> Manuela Kirchner [manuela.kirchner@daimler.com](mailto:manuela.kirchner@daimler.com), Daimler TSS GmbH, [imprint](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)

I created https://github.com/Daimler/sechub/issues/900 for this .

**Comment by de-jcup** [comment]
After some discussions, we decided, that we will change the URI and includes/excludes definitions in following style:

```json
"webScan" : {
    "uri" : "https://www.gamechanger.example.com",
    "includes" : [ "/admin//",
                         "/support"],
    "excludes": ["/support/critical-forms"]
}
```

User input validation for  excludes/includes ( will be rejected at job creation time)
- maximum amount of array entries: 500 as default (configurable per spring boot value)
- maximum amount of string length: 2048 as default (configurable per spring boot value)
- we will not allow path traversal ("../")
- they MUST start with a slash
- concatenated with their baseurl the result MUST be valid URI!

With #896 we will change the "uris" to "uri" only. So #896  will be a precondition for this issue.
