### ISSUE TITLE
Integrate SARIF web report into Sereco and improve report format

### ISSUE THREAD

**Issue by de-jcup** [mercedes-benz/sechub#606]
This is a sub issue of #9

Inside this issue we will

- implement Sereco import of the SARIF web report (we have already implemented this kind of report for OWASP Zap reporting, see #796 )
- extend Sereco add additional (optional) information (attack, evidence)
- extend SecHub HTML and JSON report (provide new optional information)
- create tests

After a while it became clear there were multiple other things to do here. So I marked the issue as an "epic", did most of the stuff here and all other in following issues (same Git branch):

Subissues:
- #946 
- #948 
- #950
- #955
- #951
- #949
- #978

**Comment by Jeeppler** [comment]
We decided to extend the OWASP ZAP report extension and add SARIF support: 

- Issue: https://github.com/zaproxy/zaproxy/issues/6875
- Pull-Request: https://github.com/zaproxy/zap-extensions/pull/3253

**Comment by de-jcup** [comment]
With last commit the report for web scan results currently looks like this:
![image](https://user-images.githubusercontent.com/11644753/150561114-8e83a8ea-fcc3-4c46-9fe6-402342e8259c.png)
 
Remark ( after the description we have also a solution block)

**Comment by Jeeppler** [comment]
How about using the [`<pre>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/pre) element for the request and response?

**Comment by Jeeppler** [comment]
And maybe wrap the `<code>` element in the `<pre>` element: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/code#notes

**Comment by de-jcup** [comment]
@Jeeppler : As discussed in our  video chat, with last commit now we have following report output:

![image](https://user-images.githubusercontent.com/11644753/150992909-0bf26860-4516-427d-8828-7002ab1b11de.png)

**Comment by Jeeppler** [comment]
@de-jcup looks good to me. Let's get it merged.
