### ISSUE TITLE
OWASP Zap - Provide OWASP ZAP PDS authenticated scans (basic auth + initial stuff)

### ISSUE THREAD

**Issue by de-jcup** [mercedes-benz/sechub#608]
This is a sub issue of #9

With #607 OWASP Zap scan was possible - but only unauthenticated

Here login support will be added:

- Extend PDSWebScanExecutor class to
  - provide credential information (see Netsparker executor class ) and provide credentials by PDS parameters
  - provide webscan login actions model data as pds parameter (base64 encoded  json content)
- Implement BasicAuth

**Comment by de-jcup** [comment]
Please look into sechub pds examples (gosec) for an easier startup (https://github.com/Daimler/sechub/tree/feature-362-pds-gosec/sechub-pds-examples/gosec)

**Comment by Jeeppler** [comment]
@winzj and @de-jcup I think this issue can be closed.
