### ISSUE TITLE
GitHub Actions "Release" shall store also developer-tools jar completely

### ISSUE THREAD

**Issue by company-jcup** [mercedes-benz/sechub#623]
## Situation
At the moment we upload only the developer-tools jar (which is pretty small) to the releases.

But unfortunately it is not executable and a combination with server jar is not enough, because we have also a dependency to the Test API parts...

# Wanted
A release shall contain the full jar (`sechub-developertools/build/libs/sechub-developer-admin-ui-....jar`)

# Solution
Change release github action

**Comment by de-jcup** [comment]
With the full jar inside the releases we do not longer need the "old" small jar - it just makes no sense and can lead to confusions.

@sven-dmlr : Please drop the old parts from github action.
