### ISSUE TITLE
Add `{noop}` to PDS Secret if missing

### ISSUE THREAD

**Issue by Jeeppler** [mercedes-benz/sechub#673]
**Problem:**

The product delegation server (PDS) does not save user passwords in a database. Instead the secrets are injected at runtime (e.g. container start). In addition, the PDS has only two users `admin` and `techuser`.

SpringBoot uses strings to indicate how the password is checked/stored. The string to indicate no hashing is used, is `{noop}`. The string needs to be added to every PDS password. In case, one forgets to add the `{noop}` the password will not work as the default SpringBoot implementation assumes the password is stored as Bcrypt hash.

**Solution:**

In case, the PDS password is not prefixed by `{noop}` add the prefix to it.

**Comment by zigfridus** [comment]
@Jeeppler 
I checked the sechub-pds project. It seems to me that {noop} has already added to every password.
Could you please check it?

**Comment by Jeeppler** [comment]
@zigfridus the product delegation server does not add `{noop}` in front of the password programmatically. All the PDS Solutions require to set the password like this:

~~~
ADMIN_USERID=admin
ADMIN_APITOKEN={noop}123mySuper$ecureAndAwsomePassword
TECHUSER_USERID=techuser
TECHUSER_APITOKEN={noop}TheMost$ecurePassword2Login!
~~~

The `{noop}` needs to be added in front. For somebody who does not know, that this is required and that `{noop}` is not part of the password, which is strange. 

The idea is to add the `{noop}` programmatically in front of the apitoken string. So that, this works:

~~~
ADMIN_USERID=admin
ADMIN_APITOKEN=123mySuper$ecureAndAwsomePassword
TECHUSER_USERID=techuser
TECHUSER_APITOKEN=TheMost$ecurePassword2Login!
~~~

Have a look at the class `PDSSecurityConfiguration` on where to add the `{noop}` in front. The `{noop}` is required by Spring Boot, which we use.

Furthermore, it might be at first counterintuitive to provide a password in plaintext and not to use `bcrypt` or other secure algorithm for the password. However, in this case we keep the password in memory and never store it. The passwords of `admin` and `techuser` need to be always "ready" for any incoming request. The passwords are never stored anywhere (at rest state), they always are in a "processing" state. We assume, that the passwords are stored in a secure location and injected into the PDS once it starts running, therefore a `bcrypt` secured password does not make sense.

**Comment by zigfridus** [comment]
Hello @Jeeppler 
Sorry for the delay.  I little busy at work at the moment.
Please assign me to this issue.

**Comment by Jeeppler** [comment]
@zigfridus I assigned you.

**Comment by zigfridus** [comment]
Hello @Jeeppler
I'm trying to run sechub-pds in the IDE. When I run **ProductDelegationServerApplication.java** in **pds_dev** profile I get this error:
`No config file found at /mnt/my_projects/sechub/git/src/test/resources/dev-pds-config.json`
The sechub project is in the /mnt/my_projects/sechub/git/ and this file is actually exists.
It seems to me that problem is in the relative path in the application-pds_dev.yml:
`sechub.pds.config.file: "src/test/resources/dev-pds-config.json"`
Maybe I run the sechub-pds in the wrong way. 
Could you please help with it?

**Comment by Jeeppler** [comment]
I have in my Eclipse IDE config the following:

- Main-Class: com.mercedesbenz.sechub.pds.ProductDelegationServerApplication

~~~ 
-Dspring.profiles.active=pds_integrationtest,pds_h2
-Dsechub.pds.storage.sharedvolume.upload.dir=/home/user/.sechub/sharedvolume
~~~

The other profile which we use mostly in the PDS solutions is `pds_localserver`. You can find a script here: https://github.com/mercedes-benz/sechub/blob/develop/sechub-pds-solutions/pds-base/docker/run.sh
