### ISSUE TITLE
Test Java 17

### ISSUE THREAD

**Issue by Jeeppler** [mercedes-benz/sechub#675]
Java 17 will be a long term release (LTS) candidate. Java 17 is expected to be released in September 2021. 

For more information have a look at: http://openjdk.java.net/projects/jdk/17/

**Comment by Jeeppler** [comment]
Java 17 will be released on the 14th of September 2021.

**Comment by Jeeppler** [comment]
Java 17 has been released on the 14th of September 2021:

- [Oracle Releases Java 17](https://www.oracle.com/news/announcement/oracle-releases-java-17-2021-09-14/)
- [JDK 17: The new features in Java 17](https://www.infoworld.com/article/3606833/jdk-17-the-new-features-in-java-17.html)

**Comment by Vivek-Prajapatii** [comment]
Can you help me in this

**Comment by Jeeppler** [comment]
First, thanks for being interested in this topic.

This issue requires on to test whether SecHub can be run and/or build with Java 17. To run / build SecHub using Java follow the instructions of the Quickstart Guide: https://daimler.github.io/sechub/latest/sechub-quickstart-guide.html. 

Please first make sure to use Java 11 as we already tested it with Java 11 and it should work well: https://github.com/Daimler/sechub/issues/187.

After using Java 11, switch your Java version to 17 and try to build it. In case it fails, report the problems this issue here. 

My assumptions are:

1. One can run SecHub with Java 17 just fine
2. The build will fail, because of Gradle #495.

However, just give it a try.

NOTE: All of this manual work is required, because we do not do an automatic matrix build with different Java versions.

**Comment by Jeeppler** [comment]
Please have a look at the Java 16 test, you might get the same issue: #613.

**Comment by Jeeppler** [comment]
Java 17 support was added in Gradle 7.3. Depends on: #495 and #1085.

**Comment by Jeeppler** [comment]
This can be tested with additional runtimes from the Adoptium Marketplace: https://adoptium.net/marketplace/.

**Comment by Jeeppler** [comment]
Eclipse Adoptium provides APIs for:

- the Temurin Java distribution: https://api.adoptium.net/
- the Adoptium marketplace: https://marketplace-api.adoptium.net/

those can be used to get the Java binary releases for OpenJ9 and Temurin.

**Comment by Jeeppler** [comment]
## Test: Debian Container

### OpenJDK Package:

The open Semeru runtime 17 (Eclipse OpenJ9 build) can be used to run SecHub, but not build it:

~~~
#15 60.37 > Task :sechub-pds:ensureLocalhostCertificate
#15 60.37 dev-base.sh: line 25: keytool: command not found
#15 60.37 Start creating localhost certificate
#15 60.37 Created file /build/sechub/sechub-pds/src/main/resources/certificates-untracked/generated-dev-localhost-keystore.p12
~~~

Apparently, there is no `keytool` command available.

Temurin 17:

Works

OpenJDK (Debian package):

Works
