### ISSUE TITLE
Introduce scan type `ANALYTICS`

### ISSUE THREAD

**Issue by Jeeppler** [mercedes-benz/sechub#681]
## Situation

SecHub does not support a scan type which collects information, but does not actually perform a security scan.

## Wanted 

Introduce a new SecHub scan type: `ANALYTICS`. The `ANALYTICS` scan type is use to gather information. `ANALYTICS` is a scan type which does not perform security testing and cannot be configured by the user via REST API. Instead SecHub will use the `ANALYTICS` tools to get information about the project/artifact which should be scanned. Getting additional information is especially important during the preprocessing phase (see #678, #680).

**Comment by de-jcup** [comment]
concept/epic see #684
