### ISSUE TITLE
Provide PDS base images inside github container registry

### ISSUE THREAD

**Issue by de-jcup** [mercedes-benz/sechub#695]
## Situation
We have with https://github.com/Daimler/sechub/tree/develop/sechub-pds-examples/gosec a `blueprint` to develop new PDS integrations (docker composite and even helm charts). But the docker file creation for PDS is always still necessary.

## Wanted
As a developer wanting to adopt a new product to SecHub by using PDS I want a ready to go docker base image where I can start with.

## Solution
What about providing base images for PDS server Alpine and Ubuntu LTE version based docker images at github container registry?

see https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry

**Comment by sven-dmlr** [comment]
Already done:
https://github.com/mercedes-benz/sechub/pkgs/container/sechub%2Fsechub-server
https://github.com/mercedes-benz/sechub/pkgs/container/sechub%2Fhelm-charts%2Fsechub-server
