### ISSUE TITLE
Mention plugins SecHub documentation

### ISSUE THREAD

**Issue by Jeeppler** [mercedes-benz/sechub#721]
## Problem

The SecHub team developed and published 3 plugins for different IDEs. The plugins allow users to navigate in SecHub reports much quicker. However, those plugins are not mentioned as part of our SecHub documentation.

## Solution

Create a new top level document in the SecHub documentation and link to all plugins in the document with a short description and screenshot.

**Comment by Jeeppler** [comment]
The plugins are already mentioned in: https://github.com/Daimler/sechub/wiki/IDE-integration

**Comment by de-jcup** [comment]
I think  we should  just add a short documentation about existing IDE-Integrations and link to https://github.com/Daimler/sechub/wiki/IDE-integration . So it would be in documentation and we have still ONE place to describe plugin features.

The plugins are note part of `SecHub` itself so I do not want to have the plugin information inside the documentation - the link would be okay.

**Comment by Jeeppler** [comment]
I would prefer to have the documentation in one place (Github Pages) and link directly to the documentation of the plugins. The plugins are not part of `SecHub`, but without `SecHub` the plugins are not very helpful.

**Comment by de-jcup** [comment]
I aggree completely. 

The github pages at https://daimler.github.io/sechub/ should have
- own header "IDE integration"
- list every plugin and  link there directly to the plugin github repository

We could also move the content (tables etc.) wiki overview from https://github.com/Daimler/sechub/wiki/IDE-integration to the github pages and link back from wiki to github pages.

So we would have all the information at the SecHub github pages.

**Comment by company-jcup** [comment]
We will change / add the IDE integration information at our sechub github page - so looks like:

## github pages

#### Documentation
		 - Technical
		 - Architecture
		 - Operations
		 - ...
		 
		 
#### IDE-integration
		- Eclipse  
		  https://github.com/daimler/sechub-plugin-eclipse
		  		  
		- VSCode/Eclipse Theia  
		  https://github.com/daimler/sechub-plugin-vscode
		  
		- IntellIJ  
		  https://github.com/daimler/sechub-plugin-intellij
		

And we we will remove the overview between the plugins from wiki.

So the information about each plugin can be found inside the plugin repository.
We will also not mention the plugins inside our Asciidoc documents. So the github pages entry site will the only and central point for users to start.
