### ISSUE TITLE
Epic: Provide binary code scans

### ISSUE THREAD

**Issue by company-jcup** [mercedes-benz/sechub#729]
## Situation
FindSecurityBugs can scan java class files - means binaries.

Currently we cannot use these kind of tools because we only support source code uploads

## Wanted
We want to provide binary uploads and provide these information to dedicated products

## Solution
- create concept
- define syntax format for configuration
- more...

**Comment by Jeeppler** [comment]
It should be possible to upload byte code/binary code for the code scan module.

Furthermore, there should be a new module for malware analysis. The reason, malware analysis requires different settings and will produce a very different report. However, both code scan and malware analysis require the ability to upload binary files.

**Comment by de-jcup** [comment]
- With #1098 we will have a `data` section inside SecHub configuration model which gives us the possiblity to define and use source and also binary  content via different scanTypes on same configuration (so only one upload).
- With #1154 we provide the upload to server side via REST
- With #1155 we provide the upload mechanism by client

**Comment by de-jcup** [comment]
We have done all issues about this, so close the epic.
