### ISSUE TITLE
Client: New command `overrideAllFalsePositives`

### ISSUE THREAD

**Issue by jtaulien-daimler** [mercedes-benz/sechub#755]
Hi :)

Please add a new command `overrideAllFalsePositives` that awaits the same file as `markFalsePositives`. But in contrast to `markFalsePositives` the new command should throw away all previously marked false positives and should then add all the new false positives from the provided file.

Why?
Like we discussed in the meeting, we would like to have a false positive file as a single source of truth in our repository and plan to use the new command `overrideAllFalsePositives` in our pipeline to update the false positives prior to executing the scan.

**Comment by sven-dmlr** [comment]
The action will be called `defineFalsePositives`.

Closing this issue in favor of #2077.  Please check there for the details of the implementation.
