### ISSUE TITLE
PMD + PDS

### ISSUE THREAD

**Issue by Jeeppler** [mercedes-benz/sechub#764]
[PMD](https://pmd.github.io/) checks for quality rules. It has some security rules. PMD supports multiple programming languages (Apex, Java [+ Java Server Pages], EMACScript [JavaScript]).

The rules can be activated to ensure PMD scans only for security rules.

Here is an example, scanning [Java Juliet 1.3](https://samate.nist.gov/SARD/testsuite.php) test cases:

~~~
./run.sh pmd -rulesets category/java/security.xml,category/jsp/security.xml  -format sarif -dir ~/Juliet/src/testcases/CWE506_Embedded_Malicious_Code
~~~

Example SARIF output:

~~~json
{
  "$schema": "https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json",
  "version": "2.1.0",
  "runs": [
    {
      "tool": {
        "driver": {
          "name": "PMD",
          "version": "6.37.0",
          "informationUri": "https://pmd.github.io/pmd/",
          "rules": [
            {
              "id": "HardCodedCryptoKey",
              "shortDescription": {
                "text": "Do not use hard coded encryption keys"
              },
              "fullDescription": {
                "text": "\nDo not use hard coded values for cryptographic operations. Please store keys outside of source code.\n        "
              },
              "helpUri": "https://pmd.github.io/pmd-6.37.0/pmd_rules_java_security.html#hardcodedcryptokey",
              "help": {
                "text": "\nDo not use hard coded values for cryptographic operations. Please store keys outside of source code.\n        "
              },
              "properties": {
                "ruleset": "Security",
                "priority": 3,
                "tags": [
                  "Security"
                ]
              }
            }
          ]
        }
      },
      "results": [
        {
          "ruleId": "HardCodedCryptoKey",
          "ruleIndex": 0,
          "message": {
            "text": "Do not use hard coded encryption keys"
          },
          "locations": [
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "/home/developer/Evaluation/Java/Java/src/testcases/CWE506_Embedded_Malicious_Code/CWE506_Embedded_Malicious_Code__aes_encrypted_payload_01.java"
                },
                "region": {
                  "startLine": 39,
                  "startColumn": 57,
                  "endLine": 39,
                  "endColumn": 74
                }
              }
            },
…
~~~

It does not support the CWE taxonomy in SARIF.

Furthermore, it is under a BSD Style / Apache 2.0 License.

## Issues belonging to this epic

* #1353

**Comment by Vivek-Prajapatii** [comment]
hey @Jeeppler i'm new to opensource and i'm interested to do this
can you please brief me about it how to get started.

**Comment by Jeeppler** [comment]
Hello @Vivek-Prajapatii,

we have an example project which you can use as starting point: https://github.com/Daimler/sechub/tree/develop/sechub-pds-examples/gosec. The example project uses [GoSec](https://github.com/securego/gosec) as static analysis tool.

The easiest way to start is, to focus first on a single instance of PDS + PMD. We use `docker` and `docker-compose` to run a single instance and an entire cluster of PDS + PMD locally. We use Helm to deploy the images to Kubernetes clusters. Basically, to do the full integration three steps are necessary:

1. Single PDS + PMD
2. Cluster of PDS + PMD
3. Helm Chart

each step builds on the previous one. The first step is the most important one.

To start creating a single instance of PDS + PMD do the following:

1. Fork SecHub and create a new branch named `feature-764-pmd`
2. Create a new folder called `pmd` under `sechub-pds-examples`: `sechub-pds-examples/pmd`.
3. Copy `01-start-single-docker-compose.sh`, `70-test.sh`, `docker-compose_pds_gosec_ubuntu.yaml`, `env-initial`, `docker/GoSec-Ubuntu.dockerfile`, `docker/gosec.sh`, `docker/pds-config.json` and `docker/run.sh`
4. Replace `gosec` with `pmd` in the filenames.
5. Remove the Go and GoSec specific parts in `docker/GoSec-Ubuntu.dockerfile` (you should have renamed to file to `docker/PMD-Ubuntu.dockerfile` by now).
6. Install PMD in the container by downloading the latest PMD release and extracting it to `/tools/pmd` inside the container.
7. Adjust the username in `docker/PMD-Ubuntu.dockerfile`.
8. Work on the `pds-config.json` file. The `id` and `serverId` fields are important. Most important is the path to the Bash wrapper script, which executes the actual PMD scan.
9. Rename `gosec.sh` to `pmd.sh`. This is the Bash wrapper script which starts the actual PMD scans. There are two important things to note here: 1) The `$PDS_JOB_RESULT_FILE` variable points to the actual result SARIF file. 2) The `$PDS_JOB_SOURCECODE_UNZIPPED_FOLDER/` points to the unzipped source code, which will be scanned by PMD.
10. Replace `PDS_GOSEC` with `PDS_PMD` (`id` field in the `pds-config.json` file): https://github.com/Daimler/sechub/blob/develop/sechub-pds-examples/gosec/70-test.sh#L83. At this point, you should able to scan source code using `70-test.sh`.

Feel free to ask any questions you have along the way.

**Comment by zigfridus** [comment]
Assign me to this issue please.

**Comment by zigfridus** [comment]
Hello @Jeeppler 
I would like to specify. You mentioned that **pmd** folder should be under the **sechub-pds-examples**. But I didn't find it. Maybe you meant **sechub-pds-solutions** folder ?
Thanks

**Comment by Jeeppler** [comment]
@zigfridus yes, the `pmd` folder should be under `sechub-pds-solutions`.

**Comment by zigfridus** [comment]
Hello @Jeeppler 
I've completed the first step : 1. Single PDS + PMD.
Should I upload the result here or at first complete other steps too?
Thanks

**Comment by Jeeppler** [comment]
@zigfridus you can upload the results one-by-one. It is easier to work on smaller tasks, rather than big tasks. Please create issues for each work package you complete. That makes it easy to track the progress.

I made an `epic` out of this issue. The epics only exist on a logical level and help to group issues together. This is a way we at SecHub work around the limitations of GitHub and keep our work organized.

**Comment by Jeeppler** [comment]
@zigfridus thanks for implementing the PMD+PDS solution 🥇 . It took several steps and we are happy you implemented each of them one-by-one. We appreciate your persistence in getting the feature implemented.

**Comment by zigfridus** [comment]
@Jeeppler 
Thank you for your detailed instructions. They were very helpful for me.
