### ISSUE TITLE
Provide latest version links at documentation page with refresh actions

### ISSUE THREAD

**Issue by company-jcup** [mercedes-benz/sechub#768]
## Situation
For automated client updates users would like to have an URL for the latest client release. So they can download binaries from the release directly.

Currently this is not possible, because "latest" release can be a client, a pds or even a server release.

## Wanted
Provide a URL at the documentation pages which gives users a redirect to the corresponding latest xyz release.

## Solution
We provide at our static page (https://mercedes-benz.github.io/sechub/) links to sub pages for each latest versions for different types
e.g.

https://mercedes-benz.github.io/sechub/latest/client.html
https://mercedes-benz.github.io/sechub/latest/server.html
https://mercedes-benz.github.io/sechub/latest/pds.html

and provide refresh / redirect mechanism via 
```
<html>
<head>
   <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
   <meta http-equiv="refresh" content="0; URL=http://example.com/">
   <title>Main Page</title>
</head>
<body></body>
</html>
```

Those pages must be generated at documentation level when dedicated new tags are set - e.g. a `v3.0.0-server`

**Comment by Jeeppler** [comment]
For more information how the http-equiv.refresh redirect works have a look at:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Redirections

For browser support have a look at:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta#attr-http-equiv

**Comment by sven-dmlr** [comment]
We just agreed in the team these urls:
```
https://mercedes-benz.github.io/sechub/latest/client-download.html
https://mercedes-benz.github.io/sechub/latest/server-download.html
https://mercedes-benz.github.io/sechub/latest/pds-download.html
```
