### ISSUE TITLE
Increase Minimum Supported Java Version To 11

### ISSUE THREAD

**Issue by Jeeppler** [mercedes-benz/sechub#784]
Java 8 was released a long time ago in 2014. Java 17 is approaching soon #675. Once Java 17 is available, there will be three LTS versions Java 8, 11 and 17. SecHub want's to support two Java LTS versions at any time.

**Comment by Vivek-Prajapatii** [comment]
Interested help me to do this

**Comment by Jeeppler** [comment]
This is a decision, rather than an issue to actively work on.

To understand the context. Currently, we still write code which is compatible with Java 8. There are some nice improvements which were introduced in Java 11 and 17. For example, [multi-line strings](https://www.baeldung.com/java-multiline-string). Currently, we cannot make use of those nice improvements.

The future plan is to set the minimum Java version to Java 11. However, SpringBoot decided to go beyond Java 11 and increase the minimum supported version for SpringBoot 3 (+Spring Framework 6) to Java 17. We probably adopt Java 17 as minimal version the moment we switch to SpringBoot 3. SecHub and the community has to decide when and how we want to switch to SpringBoot 3.

Before SpringBoot 3 we have to implement a couple of changes:

1. Test running and building SecHub with Java 17 (see: #675)
2. Upgrade to SpringBoot 2.6 (see: #691)
3. Upgrade to Gradle 7.0 (see: #495)
4. Upgrade to SpringBoot 2.7 (see: #915)
