### ISSUE TITLE
Client must inspect the status field in sechub report and react 

### ISSUE THREAD

**Issue by de-jcup** [mercedes-benz/sechub#835]
## Situation
Currently the client only inspects findings and breaks on high findings. Technical errors are only recognized when they have an "artifical" high or critical finding.

## Wanted
After #976 the client must check for a status field as well

## Solution
When status field is not `SUCCESS` but `FAILED`, the client must produce a dedicated error that the job execution failed and return an exit code != 0

**Comment by sven-dmlr** [comment]
With #976 , the `getStatus` call will return additional messages/job status.
So without needing to download a report, the result and additional messages about the job can be obtained and should be reported by the SecHub client.

Waiting for #976 to be finished before implementing this task.
