### ISSUE TITLE
Make timeout and check period configurable at runtime for checkmarx

### ISSUE THREAD

**Issue by company-jcup** [mercedes-benz/sechub#850]
## Situation
Currently we must redeploy SecHub server to change checkmarx time periods - see code:
https://github.com/Daimler/sechub/blob/02008cb69a996a5beba593da97120248c331d4c0/sechub-scan-product-checkmarx/src/main/java/com/daimler/sechub/domain/scan/product/checkmarx/CheckmarxProductExecutor.java#L43-L49

```java
    @Value("${sechub.adapter.checkmarx.scanresultcheck.period.minutes:-1}")
    @MustBeDocumented(AbstractAdapterConfigBuilder.DOCUMENT_INFO_CHECK_IN_MINUTES)
    private int scanResultCheckPeriodInMinutes;

    @Value("${sechub.adapter.checkmarx.scanresultcheck.timeout.minutes:-1}")
    @MustBeDocumented(AbstractAdapterConfigBuilder.DOCUMENT_INFO_TIMEOUT_IN_MINUTES)
    private int scanResultCheckTimeOutInMinutes;

```

## Wanted
Change without restart

## Solution

- [ ] provide and use this inside config support...
- [ ] remove `sechub.adapter.checkmarx.scanresultcheck.period.minutes` and `sechub.adapter.checkmarx.scanresultcheck.timeout.minutes` spring value parts
- [ ] provide runtime configuration by ~~`checkmarx.scanresultcheck.period.minutes`~~ `checkmarx.scanresultcheck.period.milliseconds` (see #2278) and `checkmarx.scanresultcheck.timeout.minutes`
- [ ] update documentation

**Comment by de-jcup** [comment]
Will be unnecessary, because we do 
- #1416

and the PDS checkmarx way does already provide runtime parameters for this!
