### ISSUE TITLE
Provide OWASP ZAP

### ISSUE THREAD

**Issue by de-jcup** [mercedes-benz/sechub#9]
## Situation
At the moment we only provide one SAST component: netsparker

## Wanted
We want to provide OWASP ZAP as SAST component (FOSS alternative) into SecHub. See
https://www.owasp.org/index.php/OWASP_Zed_Attack_Proxy_Project

## Solution

- We integrate Owasp zap by PDS approach.
- We use this issue as an epic until we have
  - Sereco and Report Support for OWASP
  - Full PDS integration
  - Full login support

- Work is done in "sub issues" linked inside this issue.

**Comment by de-jcup** [comment]
Hello @cschneider4711 , we met a JAX 2019 in mainz...

At your security training I have seen and used OWASP ZAP . 

Have you any information if there is an existing solution to have got ZAP inside a ready-to-use web application which could be used by SecHub? I think Arachni would be much easier to integrate (https://github.com/Daimler/sechub/issues/10) but maybe ZAP could be also a part of supported products by SecHub.

**Comment by winzj** [comment]
To track OWASP ZAP related issues we use labels, especially the `label:"owasp zap" ` (https://github.com/mercedes-benz/sechub/issues?q=is%3Aissue+is%3Aopen+label%3A%22owasp+zap%22).
Because of this, this issue will be closed.
