### ISSUE TITLE
Upgrade to Spring Boot 2.7

### ISSUE THREAD

**Issue by Jeeppler** [mercedes-benz/sechub#915]
SpringBoot 2.7 will be released in May 2022: https://spring.io/projects/spring-boot#support

A M1 release is scheduled for January 2022: https://github.com/spring-projects/spring-boot/milestone/235.

**Comment by Jeeppler** [comment]
The SpringBoot 2.7.0 M1 release is available: https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.7.0-M1-Release-Notes

**Comment by Jeeppler** [comment]
Spring Boot 2.7.0 RC1 release is available: https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.7.0-RC1-Release-Notes

**Comment by Jeeppler** [comment]
Spring Boot 2.7.0 is now available: https://spring.io/blog/2022/05/19/spring-boot-2-7-0-available-now

**Comment by de-jcup** [comment]
### Analyse of failing DB tests

Added 
```
ext['h2.version'] = '2.1.214'
```
to `build.gradle`

on develop branch (which uses 2.6.7) 

the same problems appear. So it is clear the reason of the failing tests is the `h2` upgrade.
