### ISSUE TITLE
Introduce SecHub server project job list for users

### ISSUE THREAD

**Issue by sven-dmlr** [mercedes-benz/sechub#928]
# Situation:
- It's desirable for a user to be able to download the latest report for a project without knowing the SecHub job UUID. https://daimler.github.io/sechub/latest/sechub-restapi.html#user-downloads-sechub-job-report
- It's desirable for a user to be able to get the status of a project's latest scan job without knowing the SecHub job UUID. https://daimler.github.io/sechub/latest/sechub-restapi.html#user-checks-sechub-job-state

See #545 for details and client part.

# Solution:
For both above mentioned api-requests:
accept "latest" as a job UUID. E.g.:
- `curl 'https://sechub.example.com/api/project/project1/job/latest' -i -X GET`
- `curl 'https://sechub.example.com/api/project/project1/report/latest' -i -X GET`

**Comment by de-jcup** [comment]
@sven-dmlr : I would suggest, to only implement "get latest job" --> just one use case to document and enough.
                      Inside DAUI we can implement this (x = fetch last job --> feetch report for x). 
                      Inside client we could do same.
                      An additional rest end point for latest job is not neccessary IMO

**Comment by de-jcup** [comment]
@sven-dmlr : maybe we should instead provide following:

`curl 'https://sechub.example.com/api/project/project1/job/list -i -X GET`
`curl 'https://sechub.example.com/api/project/project1/job/list?amount=1 -i -X GET`

So without the argument, a job list is returned with all run jobs (except removed ones)
The result should look like:
```json
{
  "project" : "project1",
   "jobs" : [
    {
          "jobUUID" : "$jobUUID",
          "owner" : "$startedByUserID"
     }      
   ]
}
```

It shall be ordered by creation time.
When somebody wants exact details, he/she can fetch job details

--> we keep the REST Api small, but we can introduce convenience features inside client, DAUI and later webui

**Comment by sven-dmlr** [comment]
@de-jcup That sounds good. :+1: 

Two additional thoughts:
- we should limit the number of returned list items on server side (currently, we have projects with more than 23000 scans)

- I'd propose to have the same plain list format as for `/api/admin/project/$project/scan/logs` (https://mercedes-benz.github.io/sechub/latest/sechub-restapi.html#admin-shows-scan-logs-for-project)
  This is easier to handle and consistent to the admin call. It looks like this:
```json
[
  {
    "sechubJobUUID": "$JobUUID",
    "executedBy": "$startedByUserID",
    "started": "$startDate",
    "ended": "$endDate",
    "status": "OK"
  }
]
```

p.s.: IMHO the admin call should also limit the number of returned items.

**Comment by de-jcup** [comment]
I will add a "trafficLight" entry, because this information is also very useful for an user. So we have

```json
[
  {
    "sechubJobUUID": "$JobUUID",
    "executedBy": "$startedByUserID",
    "started": "$startDate",
    "ended": "$endDate",
    "status": "OK",
    "trafficLight" : "YELLOW"
  }
]
```
as output

**Comment by de-jcup** [comment]
Will introduce spring value `sechub.project.joblist.limit.max` to define max limit per environment entry.
If there is a need for a global configuration in database we will create a new issue and implement this later.
