### ISSUE TITLE
Client: High RAM-usage while upload

### ISSUE THREAD

**Issue by olFi95** [mercedes-benz/sechub#933]
In my project we did an cov-build that yielded an emit-db with ~12.3GB.
When i do an `sechub scan`, the RAM usage jumps to 27+GB while the upload step is running.

<sup>Florian Dobisch<florian.dobisch@daimler.com>, Daimler TSS GmbH, [Provider Information](https://github.com/Daimler/daimler-foss/blob/master/PROVIDER_INFORMATION.md)</sup>

**Comment by sven-dmlr** [comment]
Checked with a 11GB zip file:
- almost no memory consumption while building the .zip file
- memory consumption starts when "Uploading source zip file"
-> trying to optimize memory consumption there

**Comment by sven-dmlr** [comment]
Checked with updated client (11GB zip file):
- client's memory footprint remains at 0.0% of memory (64GB total RAM)
