### ISSUE TITLE
PDS GoSec report does not contain name but description

### ISSUE THREAD

**Issue by de-jcup** [mercedes-benz/sechub#957]
## Situation
There is a bug inside the gosec sarif output - I created https://github.com/securego/gosec/issues/768 for it.

So for example in our HTML reports the type column (internally it uses the name attribute) does not show up "Cross site scripting" for CWE-79 but a description.
![image](https://user-images.githubusercontent.com/11644753/151166699-311e65c6-f908-4df6-ba98-bccc366d6421.png)

## Solution
We must wait until the bug has been fixed in gosec and just use the new version inside our `pds solution`
@Jeeppler , @sven-dmlr  - as long as the implementation is not fixed inside gosec we will have reports with wrong naming

**Comment by de-jcup** [comment]
PR is merged. So will be fixed in gosec > v2.9.6

**Comment by Jeeppler** [comment]
This is still an issue even with GoSec 2.10 and SecHub Server 0.29.1. Tested with: https://github.com/Contrast-Security-OSS/go-test-bench.

~~~
./gosec -version 
Version: 2.10.0
Git tag: v2.10.0
Build date: 2022-02-22T20:39:42Z
~~~

![image](https://user-images.githubusercontent.com/2007739/157467837-0b907ac9-6718-4816-9a68-ccf00d909a6e.png)

**Comment by sven-dmlr** [comment]
Meanwhile, the issue is fixed upstream. The HTML report now looks good:
![image](https://github.com/mercedes-benz/sechub/assets/59958584/973bef55-dad5-4993-8e2b-6be5c0385305)
