### ISSUE TITLE
Update Gosec to > v2.9.6

### ISSUE THREAD

**Issue by de-jcup** [mercedes-benz/sechub#968]
## Situation
https://github.com/mercedes-benz/sechub/issues/957 is fixed in gosec versoin >2.9.6 so we need to update

## Wanted
When GoSec 2.9.7 or later is available change gosec version in pds solution

This will 
- close #967
- close #957 

## Solution
When new gosec version is available update docker file / pds solution

**Comment by Jeeppler** [comment]
GoSec 2.10 is out: https://github.com/securego/gosec/releases/tag/v2.10.0
