### ISSUE TITLE
Extend time frame for api token download link

### ISSUE THREAD

**Issue by haerter-tss** [mercedes-benz/sechub#975]
Currently the initial download link for the api token is valid for 24h. It would be good if this time period could be extended, possibly through a variable that is set at server creation.

**Comment by zigfridus** [comment]
@Jeeppler 
Please assign me to this issue.

**Comment by Jeeppler** [comment]
@haerter-tss  and @zigfridus as I just figured out, that is already possible through the variable at server creation: `sechub.user.onetimetoken.outdated.millis` (see: https://mercedes-benz.github.io/sechub/latest/sechub-techdoc.html#section-general-configuration).

I am closing this issue.
